import { registerAs } from '@nestjs/config';

export const iamConfig = registerAs('iam', () => {
    return {
        passwordLessAuth: (process.env.IAM_PASSWORD_LESS_AUTH?.trim() ?? 'false') === 'true',
        passwordBasedAuth: (process.env.IAM_PASSWORD_BASED_AUTH?.trim() ?? 'true') === 'true',
        passwordlessRegistrationValidateWhat: (process.env.IAM_PASSWORD_LESS_REGISTRATION_VALIDATE_WHAT ?? 'email').split(',').map((item) => item.trim()),
        allowPublicRegistration: (process.env.IAM_ALLOW_PUBLIC_REGISTRATION ?? 'true') === 'true',
        activateUserOnRegistration: (process.env.IAM_ACTIVATE_USER_ON_REGISTRATION ?? 'true') === 'true',
        autoLoginUserOnRegistration: (process.env.IAM_AUTO_LOGIN_USER_ON_REGISTRATION ?? 'false') === 'true',
        otpExpiry: parseInt(process.env.IAM_OTP_EXPIRY ?? '10'),
        forgotPasswordVerificationTokenExpiry: parseInt(process.env.IAM_FORGOT_PASSWORD_VERIFICATION_TOKEN_EXPIRY ?? '10'),
        defaultRole: process.env.IAM_DEFAULT_ROLE ?? 'Public',
        dummyOtp: process.env.IAM_OTP_DUMMY,
        forgotPasswordSendVerificationTokenOn: process.env.IAM_FORGOT_PASSWORD_SEND_VERIFICATION_TOKEN_ON ?? 'email',
        forceChangePasswordOnFirstLogin:false,
        PASSWORD_REGEX: process.env.PASSWORD_REGEX || '^$|^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^\\da-zA-Z]).*$',
        PASSWORD_REGEX_ERROR_MESSAGE: process.env.PASSWORD_REGEX_ERROR_MESSAGE || 'Password must contain at least one uppercase, one lowercase, one number, and one special character.',
        PASSWORD_COMPLEXITY_DESC : process.env.PASSWORD_COMPLEXITY_DESC || 'Password must contain at least one uppercase, one lowercase, one number, and one special character.',
        googleOauth: {
            clientID: process.env.IAM_GOOGLE_OAUTH_CLIENT_ID,
            clientSecret: process.env.IAM_GOOGLE_OAUTH_CLIENT_SECRET,
            callbackURL: process.env.IAM_GOOGLE_OAUTH_CALLBACK_URL,
            redirectURL: process.env.IAM_GOOGLE_OAUTH_REDIRECT_URL,
        },
        iamAutoGeneratedPassword:process.env.IAM_AUTOGENERATED_PASSWORD || true,
        passwordPepper: process.env.IAM_PASSWORD_PEPPER || '', // Adding a pepper to the password hashing process for extra security,
        showNameFieldsForRegistration:process.env.IAM_SHOW_NAME_FIELDS_FOR_REGISTRATION === 'true' ? true : false,
    };
})

