import { ApiProperty } from "@nestjs/swagger";
import { Type } from "class-transformer";
import {
    IsArray,
    IsBoolean,
    IsEnum,
    IsInt,
    IsObject,
    IsOptional,
    IsString,
    ValidateNested,
} from "class-validator";
import { OrmType, SolidFieldType } from "./create-field-metadata.dto";
import { LegacyTableType } from "src/enums/legacy-table-type.enum";

export class DatasourceIntrospectionMappingColumnDto {
    @ApiProperty()
    @IsString()
    columnName: string;

    @ApiProperty()
    @IsString()
    fieldName: string;

    @ApiProperty()
    @IsString()
    displayName: string;

    @ApiProperty()
    @IsString()
    dataType: string;

    @ApiProperty({ enum: SolidFieldType })
    @IsEnum(SolidFieldType)
    solidFieldType: SolidFieldType;

    @ApiProperty()
    @IsString()
    ormType: OrmType;

    @ApiProperty()
    @IsBoolean()
    nullable: boolean;

    @ApiProperty({ required: false, nullable: true })
    @IsOptional()
    defaultValue?: string | null;

    @ApiProperty({ required: false, nullable: true })
    @IsOptional()
    @IsInt()
    characterMaximumLength?: number | null;

    @ApiProperty({ required: false, nullable: true })
    @IsOptional()
    @IsInt()
    numericPrecision?: number | null;

    @ApiProperty({ required: false, nullable: true })
    @IsOptional()
    @IsInt()
    numericScale?: number | null;

    @ApiProperty({ required: false, nullable: true })
    @IsOptional()
    @IsInt()
    ordinalPosition?: number | null;

    @ApiProperty()
    @IsBoolean()
    isAutoGenerated: boolean;

    @ApiProperty()
    @IsBoolean()
    handledBySuperclass: boolean;

    @ApiProperty({ required: false, nullable: true })
    @IsOptional()
    @IsString()
    superclassFieldName?: string | null;

    @ApiProperty({ required: false, nullable: true })
    @IsOptional()
    @IsInt()
    fieldId?: number | null;

    @ApiProperty()
    @IsBoolean()
    include: boolean;

    @ApiProperty()
    @IsBoolean()
    matched: boolean;

    @ApiProperty()
    @IsBoolean()
    isPrimaryKey: boolean;
}

export class DatasourceIntrospectionMappingDto {
    @ApiProperty()
    @IsBoolean()
    mapped: boolean;

    @ApiProperty({ required: false, nullable: true })
    @IsOptional()
    @IsInt()
    modelId?: number | null;

    @ApiProperty()
    @IsString()
    singularName: string;

    @ApiProperty()
    @IsString()
    pluralName: string;

    @ApiProperty()
    @IsString()
    displayName: string;

    @ApiProperty()
    @IsString()
    description: string;

    @ApiProperty()
    @IsString()
    tableName: string;

    @ApiProperty({ required: false, nullable: true })
    @IsOptional()
    @IsString()
    schema?: string | null;

    @ApiProperty()
    @IsString()
    dataSource: string;

    @ApiProperty()
    @IsString()
    dataSourceType: string;

    @ApiProperty({ enum: LegacyTableType })
    @IsEnum(LegacyTableType)
    legacyTableType: LegacyTableType;

    @ApiProperty()
    @IsString()
    baseClassName: string;

    @ApiProperty()
    @IsString()
    userKeyField: string;

    @ApiProperty()
    @IsBoolean()
    enableAuditTracking: boolean;

    @ApiProperty()
    @IsBoolean()
    enableSoftDelete: boolean;

    @ApiProperty()
    @IsBoolean()
    draftPublishWorkflow: boolean;

    @ApiProperty()
    @IsBoolean()
    internationalisation: boolean;

    @ApiProperty({ required: false, nullable: true })
    @IsOptional()
    @IsInt()
    plannedMigrationTimestamp?: number | null;

    @ApiProperty({ type: () => [DatasourceIntrospectionMappingColumnDto] })
    @IsArray()
    @ValidateNested({ each: true })
    @Type(() => DatasourceIntrospectionMappingColumnDto)
    columns: DatasourceIntrospectionMappingColumnDto[];

    @ApiProperty({ required: false, type: "object" })
    @IsOptional()
    @IsObject()
    reviewedModel?: Record<string, any>;
}

export class DatasourceIntrospectionRunMigrationDto {
    @ApiProperty()
    @IsString()
    datasource: string;
}
