import { Injectable } from "@nestjs/common";
import { Environment } from "src/decorators/disallow-in-production.decorator";
import { SettingsProvider } from "src/decorators/settings-provider.decorator";
import {
  ISettingsProvider,
  SettingDefinition,
  SettingLevel,
} from "src/interfaces";

export const DEFAULT_MEDIA_UPLOAD_DIR = "media-uploads";
export const DEFAULT_MEDIA_FILE_STORAGE_DIR = "media-files-storage";

// 1.
const getSolidCoreSettings = (isProd: boolean) =>
  [
    {
      moduleName: "solid-core",
      key: "iamGoogleOAuthEnabled",
      value: false,
      level: SettingLevel.SystemAdminEditable,
      label: "Allow Login / Signup With Google",
      group: "authentication-settings",
      sortOrder: 50,
      controlType: "boolean",
    },
    { moduleName: "solid-core", key: "iamFacebookOAuthEnabled", value: false, level: SettingLevel.SystemAdminEditable },
  { moduleName: "solid-core", key: "iamMicrosoftOAuthEnabled", value: false, level: SettingLevel.SystemAdminEditable },
  {
      moduleName: "solid-core",
      key: "authPagesLayout",
      value: "center",
      level: SettingLevel.SystemAdminEditable,
      label: "Authentication Screen Layout",
      group: "authentication-settings",
      sortOrder: 80,
      controlType: "selectionStatic",
      options: [
        { label: "Left", value: "left" },
        { label: "Center", value: "center" },
        { label: "Right", value: "right" },
      ],
    },
    // Removed authPagesTheme as we are going to use the local storage based theme switching in the frontend instead of server side theme switching.
    // { moduleName: "solid-core", key: "authPagesTheme", value: "light", level: SettingLevel.SystemAdminEditable },
    {
      moduleName: "solid-core",
      key: "appLogo",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "App Logo",
      group: "app-settings",
      sortOrder: 10,
      controlType: "mediaSingle",
    },
    {
      moduleName: "solid-core",
      key: "companylogo",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Company Logo",
      group: "app-settings",
      sortOrder: 20,
      controlType: "mediaSingle",
    },
    {
      moduleName: "solid-core",
      key: "favicon",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Favicon",
      group: "app-settings",
      sortOrder: 30,
      controlType: "mediaSingle",
    },
    {
      moduleName: "solid-core",
      key: "appLogoPosition",
      value: "in_form_view",
      level: SettingLevel.SystemAdminEditable,
      label: "App Logo Position",
      group: "app-settings",
      sortOrder: 40,
      controlType: "selectionStatic",
      options: [
        { label: "In Form View", value: "in_form_view" },
        { label: "In Image View", value: "in_image_view" },
      ],
    },
    {
      moduleName: "solid-core",
      key: "showAuthContent",
      value: false,
      level: SettingLevel.SystemAdminEditable,
      label: "Show Details On Authentication Screen",
      group: "app-settings",
      sortOrder: 50,
      controlType: "boolean",
    },
    {
      moduleName: "solid-core",
      key: "appTitle",
      value: process.env.SOLID_APP_NAME || "Solid App",
      level: SettingLevel.SystemAdminEditable,
      label: "App Title",
      group: "app-settings",
      sortOrder: 60,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "appSubtitle",
      value: process.env.SOLID_APP_SUBTITLE || "",
      level: SettingLevel.SystemAdminEditable,
      label: "App Subtitle",
      group: "app-settings",
      sortOrder: 70,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "appDescription",
      value: process.env.SOLID_APP_DESCRIPTION || "",
      level: SettingLevel.SystemAdminEditable,
      label: "Description",
      group: "app-settings",
      sortOrder: 80,
      controlType: "longText",
    },
    {
      moduleName: "solid-core",
      key: "showLegalLinks",
      value: false,
      level: SettingLevel.SystemAdminEditable,
      label: "Show Legal Links",
      group: "app-settings",
      sortOrder: 90,
      controlType: "boolean",
    },
    {
      moduleName: "solid-core",
      key: "appTnc",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Terms And Conditions Link",
      group: "app-settings",
      sortOrder: 100,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "appPrivacyPolicy",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Privacy Policy Link",
      group: "app-settings",
      sortOrder: 110,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "enableDarkMode",
      value: true,
      level: SettingLevel.SystemAdminEditable,
      label: "Enable Dark Mode",
      group: "app-settings",
      sortOrder: 120,
      controlType: "boolean",
    },
    {
      moduleName: "solid-core",
      key: "copyright",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Copyright",
      group: "app-settings",
      sortOrder: 130,
      controlType: "longText",
    },
    {
      moduleName: "solid-core",
      key: "enableUsername",
      value: true,
      level: SettingLevel.SystemAdminEditable,
      label: "Enable Username",
      group: "misc-settings",
      sortOrder: 10,
      controlType: "boolean",
    },
    {
      moduleName: "solid-core",
      key: "enabledNotification",
      value: true,
      level: SettingLevel.SystemAdminEditable,
      label: "Enable Notification",
      group: "misc-settings",
      sortOrder: 20,
      controlType: "boolean",
    },
    {
      moduleName: "solid-core",
      key: "contactSupportEmail",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Contact Support Email",
      group: "misc-settings",
      sortOrder: 30,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "contactSupportDisplayName",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Contact Support Display Name",
      group: "misc-settings",
      sortOrder: 40,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "contactSupportIcon",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Contact Support Icon",
      group: "misc-settings",
      sortOrder: 50,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "authScreenRightBackgroundImage",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Authentication Right Banner Image",
      group: "authentication-settings",
      sortOrder: 90,
      controlType: "mediaSingle",
    },
    {
      moduleName: "solid-core",
      key: "authScreenLeftBackgroundImage",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Authentication Left Banner Image",
      group: "authentication-settings",
      sortOrder: 100,
      controlType: "mediaSingle",
    },
    {
      moduleName: "solid-core",
      key: "authScreenCenterBackgroundImage",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Authentication Center Background Image",
      group: "authentication-settings",
      sortOrder: 110,
      controlType: "mediaSingle",
    },
    {
      moduleName: "solid-core",
      key: "solidXGenAiCodeBuilderConfig",
      value: JSON.stringify({
        models: {
          default: {
            providerId: "",
            model: "",
            behavior: { streaming: false, custom: "" },
          },
          fast: {
            providerId: "",
            model: "",
            behavior: { streaming: false, custom: "" },
          },
        },
        providers: {},
      }),
      level: SettingLevel.SystemAdminEditable,
      encrypted: true,
      label: "AI Code Builder Configuration",
      description: "Structured configuration for AI providers and model assignments.",
      group: "ai-settings",
      sortOrder: 10,
      controlType: "custom",
      settingsWidget: "solidXGenAiCodeBuilderConfigWidget"
    },
    {
      moduleName: "solid-core",
      key: "appEncryptionKey",
      value: process.env.APP_ENCRYPTION_KEY,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "mcpEnabled",
      value: process.env.MCP_ENABLED || false,
      level: SettingLevel.SystemAdminReadonly,
      label: "MCP Enabled",
      group: "ai-settings",
      sortOrder: 20,
      controlType: "boolean",
    },
    {
      moduleName: "solid-core",
      key: "mcpServerUrl",
      value: process.env.MCP_SERVER_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "MCP Server URL",
      group: "ai-settings",
      sortOrder: 30,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "mcpApiKey",
      value: process.env.MCP_API_KEY,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "dateTimeFormat",
      value: process.env.DATE_TIME_FORMAT || "YYYY-MM-DD HH:mm:ss",
      level: SettingLevel.SystemAdminEditable,
      label: "Date Time Format",
      group: "system-settings",
      sortOrder: 10,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "dateFormat",
      value: process.env.DATE_FORMAT || "YYYY-MM-DD",
      level: SettingLevel.SystemAdminEditable,
      label: "Date Format",
      group: "system-settings",
      sortOrder: 20,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "baseUrl",
      value: process.env.BASE_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "Base URL",
      group: "system-settings",
      sortOrder: 30,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "solidAppWebsiteUrl",
      value: process.env.SOLID_APP_WEBSITE_URL,
      level: SettingLevel.SystemAdminEditable,
      label: "Solid App Website URL",
      group: "system-settings",
      sortOrder: 40,
      controlType: "shortText",
    },

    // app-builder-settings-provider.service.ts, app-builder.config.ts
    {
      moduleName: "solid-core",
      key: "moduleMetadataSeederFiles",
      value: process.env.AB_MODULE_METADATA_SEEDER_FILES ?? "",
      level: SettingLevel.SystemAdminReadonly,
      label: "Module Metadata Seeder Files",
      group: "storage-settings",
      sortOrder: 10,
      controlType: "longText",
    },
    {
      moduleName: "solid-core",
      key: "uploadDir",
      value: process.env.AB_MEDIA_UPLOAD_DIR ?? DEFAULT_MEDIA_UPLOAD_DIR,
      level: SettingLevel.SystemAdminReadonly,
      label: "Upload Directory",
      group: "storage-settings",
      sortOrder: 20,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "fileStorageDir",
      value:
        process.env.AB_MEDIA_FILE_STORAGE_DIR ?? DEFAULT_MEDIA_FILE_STORAGE_DIR,
      level: SettingLevel.SystemAdminReadonly,
      label: "File Storage Directory",
      group: "storage-settings",
      sortOrder: 30,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "defaultFileService",
      value: process.env.DEFAULT_FILE_SERVICE ?? "disk",
      level: SettingLevel.SystemAdminReadonly,
      label: "Default File Service",
      group: "storage-settings",
      sortOrder: 40,
      controlType: "selectionStatic",
      options: [
        { label: "Disk", value: "disk" },
        { label: "S3", value: "s3" },
      ],
    },

    // aws-s3-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "S3_AWS_ACCESS_KEY",
      value: process.env.S3_AWS_ACCESS_KEY,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "S3_AWS_SECRET_KEY",
      value: process.env.S3_AWS_SECRET_KEY,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "S3_AWS_REGION_NAME",
      value: process.env.S3_AWS_REGION_NAME,
      level: SettingLevel.SystemAdminReadonly,
      label: "AWS Region Name",
      group: "storage-settings",
      sortOrder: 50,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "S3_DEFAULT_BUCKET",
      value: process.env.S3_DEFAULT_BUCKET,
      level: SettingLevel.SystemAdminReadonly,
      label: "S3 Default Bucket",
      group: "storage-settings",
      sortOrder: 60,
      controlType: "shortText",
    },

    // email-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "emailProvider",
      value: process.env.COMMON_EMAIL_PROVIDER ?? "SMTPEMailService",
      level: SettingLevel.SystemAdminReadonly,
      label: "Email Provider",
      group: "email-settings",
      sortOrder: 10,
      controlType: "selectionStatic",
      options: [
        { label: "SMTP Email Service", value: "SMTPEMailService" },
        { label: "Elastic Email Service", value: "ElasticEmailService" },
      ],
    },
    {
      moduleName: "solid-core",
      key: "emailTemplateSeederFiles",
      value: process.env.COMMON_EMAIL_TEMPLATE_SEEDER_FILES,
      level: SettingLevel.SystemAdminReadonly,
      label: "Email Template Seeder Files",
      group: "email-settings",
      sortOrder: 20,
      controlType: "longText",
    },
    {
      moduleName: "solid-core",
      key: "shouldQueueEmails",
      value: (process.env.COMMON_EMAIL_SHOULD_QUEUE ?? "false") === "true",
      level: SettingLevel.SystemAdminReadonly,
      label: "Queue Emails",
      group: "email-settings",
      sortOrder: 30,
      controlType: "boolean",
    },
    {
      moduleName: "solid-core",
      key: "smtpMailHost",
      value: process.env.COMMON_SMTP_EMAIL_SMTP_HOST,
      level: SettingLevel.SystemAdminReadonly,
      label: "SMTP Mail Host",
      group: "email-settings",
      sortOrder: 40,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "smtpMailPort",
      value: +(process.env.COMMON_SMTP_EMAIL_SMTP_PORT ?? 587),
      level: SettingLevel.SystemAdminReadonly,
      label: "SMTP Mail Port",
      group: "email-settings",
      sortOrder: 50,
      controlType: "numeric",
    },
    {
      moduleName: "solid-core",
      key: "smtpMailUsername",
      value: process.env.COMMON_SMTP_EMAIL_USERNAME,
      level: SettingLevel.SystemAdminReadonly,
      label: "SMTP Mail Username",
      group: "email-settings",
      sortOrder: 60,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "smtpMailPassword",
      value: process.env.COMMON_SMTP_EMAIL_PASSWORD,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "smtpMailFrom",
      value:
        process.env.COMMON_SMTP_EMAIL_FROM ?? process.env.COMMON_EMAIL_FROM,
      level: SettingLevel.SystemAdminReadonly,
      label: "SMTP Mail From",
      group: "email-settings",
      sortOrder: 70,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "apiMailKey",
      value: process.env.COMMON_API_EMAIL_KEY,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "apiMailFrom",
      value: process.env.COMMON_EMAIL_FROM,
      level: SettingLevel.SystemAdminReadonly,
      label: "API Mail From",
      group: "email-settings",
      sortOrder: 80,
      controlType: "shortText",
    },

    // genai-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "ragServerUrl",
      value: process.env.GENAI_RAG_SERVER_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "RAG Server URL",
      group: "ai-settings",
      sortOrder: 40,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "ragServerLogin",
      value: process.env.GENAI_RAG_SERVER_LOGIN,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "ragServerPassword",
      value: process.env.GENAI_RAG_SERVER_PASSWORD,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "mcpPythonExecutable",
      value: process.env.MCP_PYTHON_EXECUTABLE,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "mcpClient",
      value: process.env.MCP_CLIENT,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "mcpRestartTouchFile",
      value: process.env.MCP_RESTART_TOUCH_FILE || "tmp/restart.touch",
      level: SettingLevel.SystemEnv,
    },

    // google-oauth-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "clientID",
      value: process.env.IAM_GOOGLE_OAUTH_CLIENT_ID,
      level: SettingLevel.SystemAdminReadonly,
      label: "Google OAuth Client ID",
      group: "oauth-settings",
      sortOrder: 10,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "clientSecret",
      value: process.env.IAM_GOOGLE_OAUTH_CLIENT_SECRET,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "callbackURL",
      value: process.env.IAM_GOOGLE_OAUTH_CALLBACK_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "Google OAuth Callback URL",
      group: "oauth-settings",
      sortOrder: 20,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "redirectURL",
      value: process.env.IAM_GOOGLE_OAUTH_REDIRECT_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "Google OAuth Redirect URL",
      group: "oauth-settings",
      sortOrder: 30,
      controlType: "shortText",
    },

  // facebook-oauth-settings-provider.service.ts
  { moduleName: "solid-core", key: "FACEBOOK_CLIENT_ID", value: process.env.IAM_FACEBOOK_OAUTH_CLIENT_ID, level: SettingLevel.SystemAdminReadonly },
  { moduleName: "solid-core", key: "FACEBOOK_CLIENT_SECRET", value: process.env.IAM_FACEBOOK_OAUTH_CLIENT_SECRET, level: SettingLevel.SystemEnv },
  { moduleName: "solid-core", key: "FACEBOOK_CALLBACK_URL", value: process.env.IAM_FACEBOOK_OAUTH_CALLBACK_URL, level: SettingLevel.SystemAdminReadonly },
  { moduleName: "solid-core", key: "FACEBOOK_REDIRECT_URL", value: process.env.IAM_FACEBOOK_OAUTH_REDIRECT_URL, level: SettingLevel.SystemAdminReadonly },

  
  // microsoft-oauth-settings-provider.service.ts
  { moduleName: "solid-core", key: "MICROSOFT_CLIENT_ID", value: process.env.IAM_MICROSOFT_OAUTH_CLIENT_ID, level: SettingLevel.SystemAdminReadonly },
  { moduleName: "solid-core", key: "MICROSOFT_CLIENT_SECRET", value: process.env.IAM_MICROSOFT_OAUTH_CLIENT_SECRET, level: SettingLevel.SystemEnv },
  { moduleName: "solid-core", key: "MICROSOFT_TENANT_ID", value: process.env.IAM_MICROSOFT_OAUTH_TENANT_ID || 'common', level: SettingLevel.SystemAdminReadonly },
  { moduleName: "solid-core", key: "MICROSOFT_CALLBACK_URL", value: process.env.IAM_MICROSOFT_OAUTH_CALLBACK_URL, level: SettingLevel.SystemAdminReadonly },
  { moduleName: "solid-core", key: "MICROSOFT_REDIRECT_URL", value: process.env.IAM_MICROSOFT_OAUTH_REDIRECT_URL, level: SettingLevel.SystemAdminReadonly },

    // iam-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "passwordLessAuth",
      value: (process.env.IAM_PASSWORD_LESS_AUTH?.trim() ?? "false") === "true",
      level: SettingLevel.SystemAdminEditable,
      label: "Password Less Authentication",
      group: "authentication-settings",
      sortOrder: 20,
      controlType: "boolean",
    },
    {
      moduleName: "solid-core",
      key: "passwordBasedAuth",
      value: (process.env.IAM_PASSWORD_BASED_AUTH?.trim() ?? "true") === "true",
      level: SettingLevel.SystemAdminEditable,
      label: "Password Based Authentication",
      group: "authentication-settings",
      sortOrder: 10,
      controlType: "boolean",
    },
    {
      moduleName: "solid-core",
      key: "passwordlessRegistrationValidateWhat",
      value: (
        process.env.IAM_PASSWORD_LESS_REGISTRATION_VALIDATE_WHAT ?? "email"
      ).trim(),
      level: SettingLevel.SystemAdminEditable,
      label: "Registration Validation Type",
      group: "authentication-settings",
      sortOrder: 30,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "passwordlessLoginValidateWhat",
      value: process.env.IAM_PASSWORD_LESS_LOGIN_VALIDATE_WHAT ?? "email",
      level: SettingLevel.SystemAdminEditable,
      label: "Login Validation Type",
      group: "authentication-settings",
      sortOrder: 40,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "allowPublicRegistration",
      value: (process.env.IAM_ALLOW_PUBLIC_REGISTRATION ?? "true") === "true",
      level: SettingLevel.SystemAdminEditable,
      label: "Public Registration",
      group: "authentication-settings",
      sortOrder: 60,
      controlType: "boolean",
    },
    {
      moduleName: "solid-core",
      key: "activateUserOnRegistration",
      value:
        (process.env.IAM_ACTIVATE_USER_ON_REGISTRATION ?? "true") === "true",
      level: SettingLevel.SystemAdminEditable,
      label: "Auto Activate User On Registration",
      group: "authentication-settings",
      sortOrder: 70,
      controlType: "boolean",
    },
    {
      moduleName: "solid-core",
      key: "autoLoginUserOnRegistration",
      value:
        (process.env.IAM_AUTO_LOGIN_USER_ON_REGISTRATION ?? "false") === "true",
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "otpExpiry",
      value: parseInt(process.env.IAM_OTP_EXPIRY ?? "10"),
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "forgotPasswordVerificationTokenExpiry",
      value: parseInt(
        process.env.IAM_FORGOT_PASSWORD_VERIFICATION_TOKEN_EXPIRY ?? "10",
      ),
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "defaultRole",
      value: process.env.IAM_DEFAULT_ROLE ?? "Public",
      level: SettingLevel.SystemAdminEditable,
      label: "Default Role",
      group: "authentication-settings",
      sortOrder: 75,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "dummyOtp",
      value: process.env.IAM_OTP_DUMMY,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "dummyOtpUsers",
      value: process.env.IAM_OTP_DUMMY_USERS,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "forgotPasswordSendVerificationTokenOn",
      value:
        process.env.IAM_FORGOT_PASSWORD_SEND_VERIFICATION_TOKEN_ON ?? "email",
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "maxFailedLoginAttempts",
      value: parseInt(process.env.IAM_MAX_FAILED_LOGIN_ATTEMPTS ?? "0"),
      level: SettingLevel.SystemAdminReadonly,
      label: "Max Failed Login Attempts",
      group: "authentication-settings",
      sortOrder: 110,
      controlType: "numeric",
    },
    {
      moduleName: "solid-core",
      key: "forceChangePasswordOnFirstLogin",
      value: false,
      level: SettingLevel.SystemAdminEditable,
      label: "Force Change Password On First Login",
      group: "authentication-settings",
      sortOrder: 120,
      controlType: "boolean",
    },
    {
      moduleName: "solid-core",
      key: "authenticationPasswordRegex",
      value:
        process.env.PASSWORD_REGEX ||
        "^$|^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^\\da-zA-Z]).*$",
      level: SettingLevel.SystemAdminEditable,
      label: "Authentication Password Regex",
      group: "authentication-settings",
      sortOrder: 130,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "authenticationPasswordRegexErrorMessage",
      value:
        process.env.PASSWORD_REGEX_ERROR_MESSAGE ||
        "Password must contain at least one uppercase, one lowercase, one number, and one special character.",
      level: SettingLevel.SystemAdminEditable,
      label: "Password Regex Error Message",
      group: "authentication-settings",
      sortOrder: 140,
      controlType: "longText",
    },
    {
      moduleName: "solid-core",
      key: "authenticationPasswordComplexityDescription",
      value:
        process.env.PASSWORD_COMPLEXITY_DESC ||
        "Password must contain at least one uppercase, one lowercase, one number, and one special character.",
      level: SettingLevel.SystemAdminEditable,
      label: "Password Complexity Description",
      group: "authentication-settings",
      sortOrder: 150,
      controlType: "longText",
    },
    {
      moduleName: "solid-core",
      key: "iamAutoGeneratedPassword",
      value: process.env.IAM_AUTOGENERATED_PASSWORD || true,
      level: SettingLevel.SystemAdminEditable,
      label: "Auto Generate Password",
      group: "authentication-settings",
      sortOrder: 160,
      controlType: "boolean",
    },
    {
      moduleName: "solid-core",
      key: "passwordPepper",
      value: process.env.IAM_PASSWORD_PEPPER || "",
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "showNameFieldsForRegistration",
      value:
        process.env.IAM_SHOW_NAME_FIELDS_FOR_REGISTRATION === "true"
          ? true
          : false,
      level: SettingLevel.SystemAdminEditable,
      label: "Show Name Fields For Registration",
      group: "authentication-settings",
      sortOrder: 170,
      controlType: "boolean",
    },
    {
      moduleName: "solid-core",
      key: "sendWelcomeEmailOnSignup",
      value:
        (
          process.env.IAM_SEND_WELCOME_EMAIL_ON_SIGNUP ?? "false"
        ).toLowerCase() === "true",
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "sendWelcomeSmsOnSignup",
      value:
        (
          process.env.IAM_SEND_WELCOME_SMS_ON_SIGNUP ?? "false"
        ).toLowerCase() === "true",
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "frontendLoginPageUrl",
      value: process.env.IAM_FRONTEND_APP_LOGIN_PAGE_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "Frontend Login Page URL",
      group: "authentication-settings",
      sortOrder: 180,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "frontendForgotPasswordPageUrl",
      value: process.env.IAM_FRONTEND_APP_FORGOT_PASSWORD_PAGE_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "Frontend Forgot Password Page URL",
      group: "authentication-settings",
      sortOrder: 190,
      controlType: "shortText",
    },

    // jwt-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "secret",
      value: process.env.IAM_JWT_SECRET,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "audience",
      value: process.env.IAM_JWT_TOKEN_AUDIENCE,
      level: SettingLevel.SystemAdminReadonly,
      label: "JWT Audience",
      group: "jwt-settings",
      sortOrder: 10,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "issuer",
      value: process.env.IAM_JWT_TOKEN_ISSUER,
      level: SettingLevel.SystemAdminReadonly,
      label: "JWT Issuer",
      group: "jwt-settings",
      sortOrder: 20,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "accessTokenTtl",
      value: parseInt(
        process.env.IAM_JWT_ACCESS_TOKEN_TTL ?? (isProd ? "1200" : "86400"),
        10,
      ),
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "refreshTokenTtl",
      value: parseInt(process.env.IAM_JWT_REFRESH_TOKEN_TTL ?? "604800", 10),
      level: SettingLevel.SystemEnv,
    },

    // queues-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "queuesDefaultBroker",
      value: process.env.QUEUES_DEFAULT_BROKER || "database",
      level: SettingLevel.SystemAdminReadonly,
      label: "Queues Default Broker",
      group: "queue-settings",
      sortOrder: 10,
      controlType: "selectionStatic",
      options: [
        { label: "Database", value: "database" },
        { label: "RabbitMQ", value: "rabbitmq" },
      ],
    },
    {
      moduleName: "solid-core",
      key: "queuesServiceRole",
      value: process.env.QUEUES_SERVICE_ROLE,
      level: SettingLevel.SystemAdminReadonly,
      label: "Queues Service Role",
      group: "queue-settings",
      sortOrder: 20,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "queuesRabbitMqUrl",
      value: process.env.QUEUES_RABBIT_MQ_URL,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "solidCliRunning",
      value: process.env.SOLID_CLI_RUNNING || "false",
      level: SettingLevel.SystemEnv,
    },

    // sms-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "smsProvider",
      value: process.env.COMMON_SMS_PROVIDER,
      level: SettingLevel.SystemAdminReadonly,
      label: "SMS Provider",
      group: "sms-settings",
      sortOrder: 10,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "smsTemplateSeederFiles",
      value: process.env.COMMON_SMS_TEMPLATE_SEEDER_FILES,
      level: SettingLevel.SystemAdminReadonly,
      label: "SMS Template Seeder Files",
      group: "sms-settings",
      sortOrder: 20,
      controlType: "longText",
    },
    {
      moduleName: "solid-core",
      key: "shouldQueueSms",
      value: (process.env.COMMON_SMS_SHOULD_QUEUE ?? "false") === "true",
      level: SettingLevel.SystemAdminReadonly,
      label: "Queue SMS",
      group: "sms-settings",
      sortOrder: 30,
      controlType: "boolean",
    },
    {
      moduleName: "solid-core",
      key: "msg91SmsUrl",
      value: process.env.COMMON_MSG91_SMS_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "MSG91 SMS URL",
      group: "sms-settings",
      sortOrder: 40,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "msg91SmsApiKey",
      value: process.env.COMMON_MSG91_SMS_API_KEY,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "twilioAccountSid",
      value: process.env.COMMON_TWILIO_ACCOUNT_SID,
      level: SettingLevel.SystemAdminReadonly,
      label: "Twilio Account SID",
      group: "sms-settings",
      sortOrder: 50,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "twilioAuthToken",
      value: process.env.COMMON_TWILIO_AUTH_TOKEN,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "twilioNumber",
      value: process.env.COMMON_TWILIO_NUMBER,
      level: SettingLevel.SystemAdminReadonly,
      label: "Twilio Number",
      group: "sms-settings",
      sortOrder: 60,
      controlType: "shortText",
    },

    // tiny-url-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "tinyUrlApiUrl",
      value: process.env.COMMON_SHORT_URL_API_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "Tiny URL API URL",
      group: "short-url-settings",
      sortOrder: 10,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "tinyUrlApiKey",
      value: process.env.COMMON_SHORT_URL_API_KEY,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "tinyUrlDomain",
      value: process.env.COMMON_SHORT_URL_DOMAIN,
      level: SettingLevel.SystemAdminReadonly,
      label: "Tiny URL Domain",
      group: "short-url-settings",
      sortOrder: 20,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "tinyUrlEnabled",
      value: (process.env.COMMON_SHORT_URL_ENABLED ?? "false") === "true",
      level: SettingLevel.SystemAdminReadonly,
      label: "Tiny URL Enabled",
      group: "short-url-settings",
      sortOrder: 30,
      controlType: "boolean",
    },

    // whatsapp-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "whatsappProvider",
      value: process.env.COMMON_WHATSAPP_PROVIDER,
      level: SettingLevel.SystemAdminReadonly,
      label: "WhatsApp Provider",
      group: "whatsapp-settings",
      sortOrder: 10,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "msg91WhatsappUrl",
      value: process.env.COMMON_WHATSAPP_API_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "MSG91 WhatsApp URL",
      group: "whatsapp-settings",
      sortOrder: 20,
      controlType: "shortText",
    },
    {
      moduleName: "solid-core",
      key: "msg91WhatsappApiKey",
      value: process.env.COMMON_WHATSAPP_API_KEY,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "msg91WhatsappIntegratedNumber",
      value: process.env.COMMON_WHATSAPP_INTEGRATED_NUMBER,
      level: SettingLevel.SystemAdminReadonly,
      label: "MSG91 WhatsApp Integrated Number",
      group: "whatsapp-settings",
      sortOrder: 30,
      controlType: "shortText",
    },
  ] as const satisfies SettingDefinition[];

// 2.
export type SolidCoreSetting = ReturnType<
  typeof getSolidCoreSettings
>[number]["key"];

// 3.
@SettingsProvider()
@Injectable()
export class SolidCoreDefaultSettingsProvider implements ISettingsProvider {
  getSettings() {
    const isProd = (process.env.ENV as Environment) === Environment.Production;
    return getSolidCoreSettings(isProd);
  }
}
