import { Injectable } from "@nestjs/common";
import { Environment } from "src/decorators/disallow-in-production.decorator";
import { SettingsProvider } from "src/decorators/settings-provider.decorator";
import {
  ISettingsProvider,
  SettingDefinition,
  SettingLevel,
} from "src/interfaces";
import { getDefaultThemeKey, getThemesByMode } from "src/theme/theme-registry";

export const DEFAULT_MEDIA_UPLOAD_DIR = "media-uploads";
export const DEFAULT_MEDIA_FILE_STORAGE_DIR = "media-files-storage";

// Seeded setting values are written once and never overwritten, so an unparseable
// env var would persist. Fall back whenever it is missing or not a positive number.
const timeoutFromEnv = (value: string | undefined, fallback: number): number => {
  const parsed = Number(value);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
};

// 1.
const getSolidCoreSettings = (isProd: boolean) =>
  [
    {
      moduleName: "solid-core",
      key: "iamGoogleOAuthEnabled",
      value: false,
      level: SettingLevel.SystemAdminEditable,
      label: "Allow Login / Signup With Google",
      group: "authentication-settings",
      sortOrder: 50,
      controlType: "boolean",
      helpText: "Shows Google as a sign-in and sign-up option on supported authentication screens.",
    },
    {
      moduleName: "solid-core",
      key: "iamFacebookOAuthEnabled",
      value: false,
      level: SettingLevel.SystemAdminEditable,
      label: "Allow Login / Signup With Facebook",
      group: "authentication-settings",
      sortOrder: 50,
      controlType: "boolean",
      helpText: "Shows Facebook as a sign-in and sign-up option on supported authentication screens.",
    },
    {
      moduleName: "solid-core",
      key: "iamMicrosoftOAuthEnabled",
      value: false,
      level: SettingLevel.SystemAdminEditable,
      label: "Allow Login / Signup With Microsoft",
      group: "authentication-settings",
      sortOrder: 50,
      controlType: "boolean",
      helpText: "Shows Microsoft as a sign-in and sign-up option on supported authentication screens.",
    },
    {
      moduleName: "solid-core",
      key: "iamMicrosoftActiveDirectoryOAuthEnabled",
      value: false,
      level: SettingLevel.SystemAdminEditable,
      label: "Allow Login / Signup With Microsoft Active Directory",
      group: "authentication-settings",
      sortOrder: 50,
      controlType: "boolean",
      helpText: "Shows Microsoft Active Directory as a sign-in and sign-up option on supported authentication screens.",
    },
    {
      moduleName: "solid-core",
      key: "authPagesLayout",
      value: "center",
      level: SettingLevel.SystemAdminEditable,
      label: "Authentication Screen Layout",
      group: "authentication-settings",
      sortOrder: 80,
      controlType: "selectionStatic",
      options: [
        { label: "Left", value: "left" },
        { label: "Center", value: "center" },
        { label: "Right", value: "right" },
      ],
      helpText: "Controls whether authentication forms are centered or shown beside a left or right visual panel.",
    },
    // Removed authPagesTheme as we are going to use the local storage based theme switching in the frontend instead of server side theme switching.
    // { moduleName: "solid-core", key: "authPagesTheme", value: "light", level: SettingLevel.SystemAdminEditable },
    {
      moduleName: "solid-core",
      key: "appLogo",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "App Logo",
      group: "app-settings",
      sortOrder: 10,
      controlType: "mediaSingle",
      helpText: "Primary application logo used across branded authentication and workspace surfaces.",
    },
    {
      moduleName: "solid-core",
      key: "companylogo",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Company Logo",
      group: "app-settings",
      sortOrder: 20,
      controlType: "mediaSingle",
      helpText: "Secondary company logo for installations that need separate corporate branding.",
    },
    {
      moduleName: "solid-core",
      key: "favicon",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Favicon",
      group: "app-settings",
      sortOrder: 30,
      controlType: "mediaSingle",
      helpText: "Browser tab icon used by the workspace and authentication pages when a custom favicon is configured.",
    },
    {
      moduleName: "solid-core",
      key: "appLogoPosition",
      value: "in_form_view",
      level: SettingLevel.SystemAdminEditable,
      label: "App Logo Position",
      group: "app-settings",
      sortOrder: 40,
      controlType: "selectionStatic",
      options: [
        { label: "In Form View", value: "in_form_view" },
        { label: "In Image View", value: "in_image_view" },
      ],
      helpText: "Controls whether the app logo appears inside the authentication form or inside the image panel.",
    },
    {
      moduleName: "solid-core",
      key: "recordClickAction",
      value: "edit",
      level: SettingLevel.SystemAdminEditable,
      label: "Record Click Action",
      group: "app-settings",
      sortOrder: 45,
      controlType: "selectionStatic",
      options: [
        { label: "Edit", value: "edit" },
        { label: "View", value: "view" },
      ],
      helpText: "Decides whether clicking a record in List, Card, Kanban, or Tree View opens it in edit mode or view mode.",
    },
    {
      moduleName: "solid-core",
      key: "showAuthContent",
      value: false,
      level: SettingLevel.SystemAdminEditable,
      label: "Show Details On Authentication Screen",
      group: "app-settings",
      sortOrder: 50,
      controlType: "boolean",
      helpText: "Shows or hides the title, subtitle, and description block on authentication screens.",
    },
    {
      moduleName: "solid-core",
      key: "appTitle",
      value: process.env.SOLID_APP_NAME || "Solid App",
      level: SettingLevel.SystemAdminEditable,
      label: "App Title",
      group: "app-settings",
      sortOrder: 60,
      controlType: "shortText",
      helpText: "Main application name shown on branded authentication screens.",
    },
    {
      moduleName: "solid-core",
      key: "appSubtitle",
      value: process.env.SOLID_APP_SUBTITLE || "",
      level: SettingLevel.SystemAdminEditable,
      label: "App Subtitle",
      group: "app-settings",
      sortOrder: 70,
      controlType: "shortText",
      helpText: "Short subtitle shown above or beside the main application title.",
    },
    {
      moduleName: "solid-core",
      key: "appDescription",
      value: process.env.SOLID_APP_DESCRIPTION || "",
      level: SettingLevel.SystemAdminEditable,
      label: "Description",
      group: "app-settings",
      sortOrder: 80,
      controlType: "longText",
      helpText: "Supporting copy used to explain the product or workspace on authentication screens.",
    },
    {
      moduleName: "solid-core",
      key: "showLegalLinks",
      value: false,
      level: SettingLevel.SystemAdminEditable,
      label: "Show Legal Links",
      group: "app-settings",
      sortOrder: 90,
      controlType: "boolean",
      helpText: "Shows or hides the terms and privacy links on authentication screens.",
    },
    {
      moduleName: "solid-core",
      key: "appTnc",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Terms And Conditions Link",
      group: "app-settings",
      sortOrder: 100,
      controlType: "shortText",
      helpText: "Terms and conditions URL shown when legal links are enabled.",
    },
    {
      moduleName: "solid-core",
      key: "appPrivacyPolicy",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Privacy Policy Link",
      group: "app-settings",
      sortOrder: 110,
      controlType: "shortText",
      helpText: "Privacy policy URL shown when legal links are enabled.",
    },
    {
      moduleName: "solid-core",
      key: "showThemeToggle",
      value: true,
      level: SettingLevel.SystemAdminEditable,
      label: "Show Theme Toggle",
      group: "app-settings",
      sortOrder: 120,
      controlType: "boolean",
      helpText: "Shows the theme toggle in the frontend so users can switch between light and dark themes.",
    },
    {
      moduleName: "solid-core",
      key: "lightTheme",
      value: getDefaultThemeKey("light"),
      level: SettingLevel.SystemAdminEditable,
      label: "Light Theme",
      group: "app-settings",
      sortOrder: 125,
      controlType: "selectionStatic",
      options: getThemesByMode("light").map((theme) => ({
        label: theme.label,
        value: theme.key,
      })),
      helpText: "Selects the theme used whenever the application is in light mode.",
    },
    {
      moduleName: "solid-core",
      key: "darkTheme",
      value: getDefaultThemeKey("dark"),
      level: SettingLevel.SystemAdminEditable,
      label: "Dark Theme",
      group: "app-settings",
      sortOrder: 126,
      controlType: "selectionStatic",
      options: getThemesByMode("dark").map((theme) => ({
        label: theme.label,
        value: theme.key,
      })),
      helpText: "Selects the theme used whenever the application is in dark mode.",
    },
    {
      moduleName: "solid-core",
      key: "copyright",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Copyright",
      group: "app-settings",
      sortOrder: 130,
      controlType: "longText",
      helpText: "Footer copyright text shown on branded authentication screens.",
    },
    {
      moduleName: "solid-core",
      key: "enableUsername",
      value: true,
      level: SettingLevel.SystemAdminEditable,
      label: "Enable Username",
      group: "misc-settings",
      sortOrder: 10,
      controlType: "boolean",
      helpText: "Allows username-based identity flows where the frontend supports them.",
    },
    {
      moduleName: "solid-core",
      key: "enabledNotification",
      value: true,
      level: SettingLevel.SystemAdminEditable,
      label: "Enable Notification",
      group: "misc-settings",
      sortOrder: 20,
      controlType: "boolean",
      helpText: "Default notification toggle used by user-facing notification settings.",
    },
    {
      moduleName: "solid-core",
      key: "contactSupportEmail",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Contact Support Email",
      group: "misc-settings",
      sortOrder: 30,
      controlType: "shortText",
      helpText: "Email address used by the support shortcut in the user menu and related help surfaces.",
    },
    {
      moduleName: "solid-core",
      key: "contactSupportDisplayName",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Contact Support Display Name",
      group: "misc-settings",
      sortOrder: 40,
      controlType: "shortText",
      helpText: "Friendly label shown for the support shortcut, such as Support or Help Desk.",
    },
    {
      moduleName: "solid-core",
      key: "contactSupportIcon",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Contact Support Icon",
      group: "misc-settings",
      sortOrder: 50,
      controlType: "shortText",
      helpText: "Icon identifier used for the support shortcut so users can recognize it quickly.",
    },
    {
      moduleName: "solid-core",
      key: "authScreenRightBackgroundImage",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Authentication Right Banner Image",
      group: "authentication-settings",
      sortOrder: 90,
      controlType: "mediaSingle",
      helpText: "Banner image used when the authentication form is shown on the left and the visual panel is on the right.",
    },
    {
      moduleName: "solid-core",
      key: "authScreenLeftBackgroundImage",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Authentication Left Banner Image",
      group: "authentication-settings",
      sortOrder: 100,
      controlType: "mediaSingle",
      helpText: "Banner image used when the authentication form is shown on the right and the visual panel is on the left.",
    },
    {
      moduleName: "solid-core",
      key: "authScreenCenterBackgroundImage",
      value: null,
      level: SettingLevel.SystemAdminEditable,
      label: "Authentication Center Background Image",
      group: "authentication-settings",
      sortOrder: 110,
      controlType: "mediaSingle",
      helpText: "Background image used for the centered authentication layout.",
    },
    {
      moduleName: "solid-core",
      key: "solidXGenAiCodeBuilderConfig",
      value: JSON.stringify({
        models: {
          default: {
            providerId: "",
            model: "",
            behavior: { streaming: false, custom: "" },
          },
          fast: {
            providerId: "",
            model: "",
            behavior: { streaming: false, custom: "" },
          },
        },
        providers: {},
      }),
      level: SettingLevel.SystemAdminEditable,
      encrypted: true,
      label: "AI Code Builder Configuration",
      description:
        "Structured configuration for AI providers and model assignments.",
      group: "ai-settings",
      sortOrder: 10,
      controlType: "custom",
      settingsWidget: "solidXGenAiCodeBuilderConfigWidget",
      helpText: "Structured AI builder configuration that stores providers, credentials, and model assignments for SolidX code generation features.",
    },
    {
      moduleName: "solid-core",
      key: "appEncryptionKey",
      value: process.env.APP_ENCRYPTION_KEY,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "mcpEnabled",
      value: process.env.MCP_ENABLED || false,
      level: SettingLevel.SystemAdminReadonly,
      label: "MCP Enabled",
      group: "ai-settings",
      sortOrder: 20,
      controlType: "boolean",
      helpText: "Read-only flag indicating whether MCP integration is enabled for this deployment.",
    },
    {
      moduleName: "solid-core",
      key: "mcpServerUrl",
      value: process.env.MCP_SERVER_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "MCP Server URL",
      group: "ai-settings",
      sortOrder: 30,
      controlType: "shortText",
      helpText: "Base MCP server URL used when MCP integration is enabled.",
    },
    {
      moduleName: "solid-core",
      key: "mcpApiKey",
      value: process.env.MCP_API_KEY,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "dateTimeFormat",
      value: process.env.DATE_TIME_FORMAT || "YYYY-MM-DD HH:mm:ss",
      level: SettingLevel.SystemAdminEditable,
      label: "Date Time Format",
      group: "system-settings",
      sortOrder: 10,
      controlType: "shortText",
      helpText: "Default date-time format used by Solid core features that need a shared server-side format.",
    },
    {
      moduleName: "solid-core",
      key: "dateFormat",
      value: process.env.DATE_FORMAT || "YYYY-MM-DD",
      level: SettingLevel.SystemAdminEditable,
      label: "Date Format",
      group: "system-settings",
      sortOrder: 20,
      controlType: "shortText",
      helpText: "Default date format used by Solid core features that need a shared server-side format.",
    },
    {
      moduleName: "solid-core",
      key: "baseUrl",
      value: process.env.BASE_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "Base URL",
      group: "system-settings",
      sortOrder: 30,
      controlType: "shortText",
      helpText: "Backend base URL used to generate absolute links and media URLs.",
    }, 
    {
      moduleName: "solid-core",
      key: "frontendAdminBaseUrl",
      value: process.env.FRONTEND_BASE_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "Frontend Admin Base URL",
      group: "system-settings",
      sortOrder: 35,
      controlType: "shortText",
      helpText: "Frontend admin application base URL used when the backend needs to point users back to the admin UI.",
    },
    {
      moduleName: "solid-core",
      key: "solidAppWebsiteUrl",
      value: process.env.SOLID_APP_WEBSITE_URL,
      level: SettingLevel.SystemAdminEditable,
      label: "Solid App Website URL",
      group: "system-settings",
      sortOrder: 40,
      controlType: "shortText",
      helpText: "Public website URL for the product or marketing site.",
    },

    // app-builder-settings-provider.service.ts, app-builder.config.ts
    {
      moduleName: "solid-core",
      key: "moduleMetadataSeederFiles",
      value: process.env.AB_MODULE_METADATA_SEEDER_FILES ?? "",
      level: SettingLevel.SystemAdminReadonly,
      label: "Module Metadata Seeder Files",
      group: "storage-settings",
      sortOrder: 10,
      controlType: "longText",
      helpText: "Comma-separated list of module metadata seed files that are loaded by the platform.",
    },
    {
      moduleName: "solid-core",
      key: "uploadDir",
      value: process.env.AB_MEDIA_UPLOAD_DIR ?? DEFAULT_MEDIA_UPLOAD_DIR,
      level: SettingLevel.SystemAdminReadonly,
      label: "Upload Directory",
      group: "storage-settings",
      sortOrder: 20,
      controlType: "shortText",
      helpText: "Directory where uploaded media is staged before downstream processing or persistence.",
    },
    {
      moduleName: "solid-core",
      key: "fileStorageDir",
      value:
        process.env.AB_MEDIA_FILE_STORAGE_DIR ?? DEFAULT_MEDIA_FILE_STORAGE_DIR,
      level: SettingLevel.SystemAdminReadonly,
      label: "File Storage Directory",
      group: "storage-settings",
      sortOrder: 30,
      controlType: "shortText",
      helpText: "Directory used by the default disk-based file storage provider for persisted files.",
    },
    {
      moduleName: "solid-core",
      key: "defaultFileService",
      value: process.env.DEFAULT_FILE_SERVICE ?? "disk",
      level: SettingLevel.SystemAdminReadonly,
      label: "Default File Service",
      group: "storage-settings",
      sortOrder: 40,
      controlType: "selectionStatic",
      options: [
        { label: "Disk", value: "disk" },
        { label: "S3", value: "s3" },
      ],
      helpText: "Default storage implementation used for file handling, such as local disk or S3.",
    },

    // aws-s3-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "S3_AWS_ACCESS_KEY",
      value: process.env.S3_AWS_ACCESS_KEY,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "S3_AWS_SECRET_KEY",
      value: process.env.S3_AWS_SECRET_KEY,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "S3_AWS_REGION_NAME",
      value: process.env.S3_AWS_REGION_NAME,
      level: SettingLevel.SystemAdminReadonly,
      label: "AWS Region Name",
      group: "storage-settings",
      sortOrder: 50,
      controlType: "shortText",
      helpText: "AWS region used by the default S3 storage integration.",
    },
    {
      moduleName: "solid-core",
      key: "S3_DEFAULT_BUCKET",
      value: process.env.S3_DEFAULT_BUCKET,
      level: SettingLevel.SystemAdminReadonly,
      label: "S3 Default Bucket",
      group: "storage-settings",
      sortOrder: 60,
      controlType: "shortText",
      helpText: "Default S3 bucket used when the S3 storage provider is active.",
    },

    // email-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "emailProvider",
      value: process.env.COMMON_EMAIL_PROVIDER ?? "SMTPEMailService",
      level: SettingLevel.SystemAdminReadonly,
      label: "Email Provider",
      group: "email-settings",
      sortOrder: 10,
      controlType: "selectionStatic",
      options: [
        { label: "SMTP Email Service", value: "SMTPEMailService" },
        { label: "Elastic Email Service", value: "ElasticEmailService" },
      ],
      helpText: "Email delivery provider currently configured for outbound mail.",
    },
    {
      moduleName: "solid-core",
      key: "emailTemplateSeederFiles",
      value: process.env.COMMON_EMAIL_TEMPLATE_SEEDER_FILES,
      level: SettingLevel.SystemAdminReadonly,
      label: "Email Template Seeder Files",
      group: "email-settings",
      sortOrder: 20,
      controlType: "longText",
      helpText: "Comma-separated list of email template seed files loaded by the platform.",
    },
    {
      moduleName: "solid-core",
      key: "shouldQueueEmails",
      value: (process.env.COMMON_EMAIL_SHOULD_QUEUE ?? "false") === "true",
      level: SettingLevel.SystemAdminReadonly,
      label: "Queue Emails",
      group: "email-settings",
      sortOrder: 30,
      controlType: "boolean",
      helpText: "Whether outbound emails are queued for asynchronous delivery instead of being sent inline.",
    },
    {
      moduleName: "solid-core",
      key: "smtpMailHost",
      value: process.env.COMMON_SMTP_EMAIL_SMTP_HOST,
      level: SettingLevel.SystemAdminReadonly,
      label: "SMTP Mail Host",
      group: "email-settings",
      sortOrder: 40,
      controlType: "shortText",
      helpText: "SMTP host name used when the SMTP email provider is active.",
    },
    {
      moduleName: "solid-core",
      key: "smtpMailPort",
      value: +(process.env.COMMON_SMTP_EMAIL_SMTP_PORT ?? 587),
      level: SettingLevel.SystemAdminReadonly,
      label: "SMTP Mail Port",
      group: "email-settings",
      sortOrder: 50,
      controlType: "numeric",
      helpText: "SMTP port used when the SMTP email provider is active.",
    },
    {
      moduleName: "solid-core",
      key: "smtpMailUsername",
      value: process.env.COMMON_SMTP_EMAIL_USERNAME,
      level: SettingLevel.SystemAdminReadonly,
      label: "SMTP Mail Username",
      group: "email-settings",
      sortOrder: 60,
      controlType: "shortText",
      helpText: "SMTP username used when the SMTP email provider is active.",
    },
    {
      moduleName: "solid-core",
      key: "smtpMailPassword",
      value: process.env.COMMON_SMTP_EMAIL_PASSWORD,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "smtpMailFrom",
      value:
        process.env.COMMON_SMTP_EMAIL_FROM ?? process.env.COMMON_EMAIL_FROM,
      level: SettingLevel.SystemAdminReadonly,
      label: "SMTP Mail From",
      group: "email-settings",
      sortOrder: 70,
      controlType: "shortText",
      helpText: "Default From address for outbound mail sent through the SMTP provider.",
    },
    {
      moduleName: "solid-core",
      key: "apiMailKey",
      value: process.env.COMMON_API_EMAIL_KEY,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "apiMailFrom",
      value: process.env.COMMON_EMAIL_FROM,
      level: SettingLevel.SystemAdminReadonly,
      label: "API Mail From",
      group: "email-settings",
      sortOrder: 80,
      controlType: "shortText",
      helpText: "Default From address for outbound mail sent through API-based email providers.",
    },

    // genai-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "ragServerUrl",
      value: process.env.GENAI_RAG_SERVER_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "RAG Server URL",
      group: "ai-settings",
      sortOrder: 40,
      controlType: "shortText",
      helpText: "Base URL of the RAG service used by AI-assisted features that need retrieval support.",
    },
    {
      moduleName: "solid-core",
      key: "ragServerLogin",
      value: process.env.GENAI_RAG_SERVER_LOGIN,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "ragServerPassword",
      value: process.env.GENAI_RAG_SERVER_PASSWORD,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "mcpPythonExecutable",
      value: process.env.MCP_PYTHON_EXECUTABLE,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "mcpClient",
      value: process.env.MCP_CLIENT,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "mcpRestartTouchFile",
      value: process.env.MCP_RESTART_TOUCH_FILE || "tmp/restart.touch",
      level: SettingLevel.SystemEnv,
    },

    // google-oauth-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "clientID",
      value: process.env.IAM_GOOGLE_OAUTH_CLIENT_ID,
      level: SettingLevel.SystemAdminReadonly,
      label: "Google OAuth Client ID",
      group: "oauth-settings",
      sortOrder: 10,
      controlType: "shortText",
      helpText: "Google OAuth client ID registered for this application.",
    },
    {
      moduleName: "solid-core",
      key: "clientSecret",
      value: process.env.IAM_GOOGLE_OAUTH_CLIENT_SECRET,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "callbackURL",
      value: process.env.IAM_GOOGLE_OAUTH_CALLBACK_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "Google OAuth Callback URL",
      group: "oauth-settings",
      sortOrder: 20,
      controlType: "shortText",
      helpText: "Backend callback URL that Google redirects to after authentication.",
    },
    {
      moduleName: "solid-core",
      key: "redirectURL",
      value: process.env.IAM_GOOGLE_OAUTH_REDIRECT_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "Google OAuth Redirect URL",
      group: "oauth-settings",
      sortOrder: 30,
      controlType: "shortText",
      helpText: "Post-authentication Google redirect URL used by the application flow.",
    },

    // facebook-oauth-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "FACEBOOK_CLIENT_ID",
      value: process.env.IAM_FACEBOOK_OAUTH_CLIENT_ID,
      level: SettingLevel.SystemAdminReadonly,
      helpText: "Facebook OAuth client ID registered for this application.",
    },
    {
      moduleName: "solid-core",
      key: "FACEBOOK_CLIENT_SECRET",
      value: process.env.IAM_FACEBOOK_OAUTH_CLIENT_SECRET,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "FACEBOOK_CALLBACK_URL",
      value: process.env.IAM_FACEBOOK_OAUTH_CALLBACK_URL,
      level: SettingLevel.SystemAdminReadonly,
      helpText: "Backend callback URL that Facebook redirects to after authentication.",
    },
    {
      moduleName: "solid-core",
      key: "FACEBOOK_REDIRECT_URL",
      value: process.env.IAM_FACEBOOK_OAUTH_REDIRECT_URL,
      level: SettingLevel.SystemAdminReadonly,
      helpText: "Post-authentication Facebook redirect URL used by the application flow.",
    },

    // microsoft-oauth-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "MICROSOFT_CLIENT_ID",
      value: process.env.IAM_MICROSOFT_OAUTH_CLIENT_ID,
      level: SettingLevel.SystemAdminReadonly,
      helpText: "Microsoft OAuth client ID registered for this application.",
    },
    {
      moduleName: "solid-core",
      key: "MICROSOFT_CLIENT_SECRET",
      value: process.env.IAM_MICROSOFT_OAUTH_CLIENT_SECRET,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "MICROSOFT_TENANT_ID",
      value: process.env.IAM_MICROSOFT_OAUTH_TENANT_ID || "common",
      level: SettingLevel.SystemAdminReadonly,
      helpText: "Microsoft OAuth tenant identifier used to scope sign-in requests.",
    },
    {
      moduleName: "solid-core",
      key: "MICROSOFT_CALLBACK_URL",
      value: process.env.IAM_MICROSOFT_OAUTH_CALLBACK_URL,
      level: SettingLevel.SystemAdminReadonly,
      helpText: "Backend callback URL that Microsoft redirects to after authentication.",
    },
    {
      moduleName: "solid-core",
      key: "MICROSOFT_REDIRECT_URL",
      value: process.env.IAM_MICROSOFT_OAUTH_REDIRECT_URL,
      level: SettingLevel.SystemAdminReadonly,
      helpText: "Post-authentication Microsoft redirect URL used by the application flow.",
    },

    // microsoft-active-directory-oauth-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "MICROSOFT_ACTIVE_DIRECTORY_CLIENT_ID",
      value: process.env.IAM_MICROSOFT_ACTIVE_DIRECTORY_OAUTH_CLIENT_ID,
      level: SettingLevel.SystemAdminReadonly,
      label: "Microsoft Active Directory OAuth Client ID",
      group: "oauth-settings",
      sortOrder: 70,
      controlType: "shortText",
      helpText: "Microsoft Active Directory client ID registered for this application.",
    },
    {
      moduleName: "solid-core",
      key: "MICROSOFT_ACTIVE_DIRECTORY_CLIENT_SECRET",
      value: process.env.IAM_MICROSOFT_ACTIVE_DIRECTORY_OAUTH_CLIENT_SECRET,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "MICROSOFT_ACTIVE_DIRECTORY_TENANT_ID",
      value:
        process.env.IAM_MICROSOFT_ACTIVE_DIRECTORY_OAUTH_TENANT_ID || "common",
      level: SettingLevel.SystemAdminReadonly,
      label: "Microsoft Active Directory OAuth Tenant ID",
      group: "oauth-settings",
      sortOrder: 80,
      controlType: "shortText",
      helpText: "Microsoft Active Directory tenant identifier used to scope sign-in requests.",
    },
    {
      moduleName: "solid-core",
      key: "MICROSOFT_ACTIVE_DIRECTORY_CALLBACK_URL",
      value: process.env.IAM_MICROSOFT_ACTIVE_DIRECTORY_OAUTH_CALLBACK_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "Microsoft Active Directory OAuth Callback URL",
      group: "oauth-settings",
      sortOrder: 90,
      controlType: "shortText",
      helpText: "Backend callback URL that Microsoft Active Directory redirects to after authentication.",
    },
    {
      moduleName: "solid-core",
      key: "MICROSOFT_ACTIVE_DIRECTORY_REDIRECT_URL",
      value: process.env.IAM_MICROSOFT_ACTIVE_DIRECTORY_OAUTH_REDIRECT_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "Microsoft Active Directory OAuth Redirect URL",
      group: "oauth-settings",
      sortOrder: 100,
      controlType: "shortText",
      helpText: "Post-authentication Microsoft Active Directory redirect URL used by the application flow.",
    },

    // iam-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "passwordLessAuth",
      value: (process.env.IAM_PASSWORD_LESS_AUTH?.trim() ?? "false") === "true",
      level: SettingLevel.SystemAdminEditable,
      label: "Password Less Authentication",
      group: "authentication-settings",
      sortOrder: 20,
      controlType: "boolean",
      helpText: "Enables passwordless sign-in flows such as OTP-based authentication.",
    },
    {
      moduleName: "solid-core",
      key: "passwordBasedAuth",
      value: (process.env.IAM_PASSWORD_BASED_AUTH?.trim() ?? "true") === "true",
      level: SettingLevel.SystemAdminEditable,
      label: "Password Based Authentication",
      group: "authentication-settings",
      sortOrder: 10,
      controlType: "boolean",
      helpText: "Enables traditional password-based sign-in.",
    },
    {
      moduleName: "solid-core",
      key: "passwordlessRegistrationValidateWhat",
      value: (
        process.env.IAM_PASSWORD_LESS_REGISTRATION_VALIDATE_WHAT ?? "email"
      ).trim(),
      level: SettingLevel.SystemAdminEditable,
      label: "Registration Validation Type",
      group: "authentication-settings",
      sortOrder: 30,
      controlType: "selectionStatic",
      options: [
        { label: "Email", value: "email" },
        { label: "Mobile", value: "mobile" },
      ],
      helpText: "Chooses whether passwordless registration validates new users by email or mobile number.",
    },
    {
      moduleName: "solid-core",
      key: "passwordlessLoginValidateWhat",
      value: process.env.IAM_PASSWORD_LESS_LOGIN_VALIDATE_WHAT ?? "email",
      level: SettingLevel.SystemAdminEditable,
      label: "Login Validation Type",
      group: "authentication-settings",
      sortOrder: 40,
      controlType: "selectionStatic",
      options: [
        { label: "Email", value: "email" },
        { label: "Mobile", value: "mobile" },
        { label: "Selectable", value: "selectable" },
      ],
      helpText: "Chooses whether passwordless login validates users by email, mobile number, or a selectable option.",
    },
    {
      moduleName: "solid-core",
      key: "allowPublicRegistration",
      value: (process.env.IAM_ALLOW_PUBLIC_REGISTRATION ?? "true") === "true",
      level: SettingLevel.SystemAdminEditable,
      label: "Public Registration",
      group: "authentication-settings",
      sortOrder: 60,
      controlType: "boolean",
      helpText: "Lets unauthenticated visitors create their own account from public registration screens.",
    },
    {
      moduleName: "solid-core",
      key: "activateUserOnRegistration",
      value:
        (process.env.IAM_ACTIVATE_USER_ON_REGISTRATION ?? "true") === "true",
      level: SettingLevel.SystemAdminEditable,
      label: "Auto Activate User On Registration",
      group: "authentication-settings",
      sortOrder: 70,
      controlType: "boolean",
      helpText: "Automatically activates newly registered users instead of requiring a separate activation step.",
    },
    {
      moduleName: "solid-core",
      key: "autoLoginUserOnRegistration",
      value:
        (process.env.IAM_AUTO_LOGIN_USER_ON_REGISTRATION ?? "false") === "true",
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "otpExpiry",
      value: parseInt(process.env.IAM_OTP_EXPIRY ?? "10"),
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "otpWhatsappFallbackEnabled",
      value: (process.env.IAM_OTP_WHATSAPP_FALLBACK_ENABLED ?? "true") === "true",
      level: SettingLevel.SystemAdminEditable,
      label: "OTP WhatsApp Fallback Enabled",
      group: "authentication-settings",
      sortOrder: 85,
      controlType: "boolean",
      helpText: "Allows OTP delivery to fall back to WhatsApp when the primary OTP path cannot be used.",
    },
    {
      moduleName: "solid-core",
      key: "otpWhatsappTemplateId",
      value: process.env.IAM_OTP_WHATSAPP_TEMPLATE_ID ?? "common_otp",
      level: SettingLevel.SystemAdminEditable,
      label: "OTP WhatsApp Template ID",
      group: "authentication-settings",
      sortOrder: 86,
      controlType: "shortText",
      helpText: "Template identifier used when OTP messages are sent through WhatsApp.",
    },
    {
      moduleName: "solid-core",
      key: "otpWhatsappIndependentEnabled",
      value: (process.env.IAM_OTP_WHATSAPP_INDEPENDENT_ENABLED ?? "true") === "true",
      level: SettingLevel.SystemAdminEditable,
      label: "OTP WhatsApp Independent Enabled",
      group: "authentication-settings",
      sortOrder: 87,
      controlType: "boolean",
      helpText: "Allows WhatsApp OTP delivery to run as an independent channel where supported.",
    },
    {
      moduleName: "solid-core",
      key: "otpDefaultCountryDialCode",
      value: process.env.IAM_OTP_DEFAULT_COUNTRY_DIAL_CODE ?? "",
      level: SettingLevel.SystemAdminEditable,
      label: "OTP Default Country Dial Code",
      group: "authentication-settings",
      sortOrder: 88,
      controlType: "shortText",
      helpText: "Default dialing code applied when OTP phone numbers are entered without a country prefix.",
    },
    {
      moduleName: "solid-core",
      key: "forgotPasswordVerificationTokenExpiry",
      value: parseInt(
        process.env.IAM_FORGOT_PASSWORD_VERIFICATION_TOKEN_EXPIRY ?? "10",
      ),
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "defaultRole",
      value: process.env.IAM_DEFAULT_ROLE ?? "Public",
      level: SettingLevel.SystemAdminEditable,
      label: "Default Role",
      group: "authentication-settings",
      sortOrder: 75,
      controlType: "shortText",
      helpText: "Role assigned by default to newly created users in flows that rely on automatic role assignment.",
    },
    {
      moduleName: "solid-core",
      key: "dummyOtp",
      value: process.env.IAM_OTP_DUMMY,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "dummyOtpUsers",
      value: process.env.IAM_OTP_DUMMY_USERS,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "forgotPasswordSendVerificationTokenOn",
      value:
        process.env.IAM_FORGOT_PASSWORD_SEND_VERIFICATION_TOKEN_ON ?? "email",
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "maxFailedLoginAttempts",
      value: parseInt(process.env.IAM_MAX_FAILED_LOGIN_ATTEMPTS ?? "0"),
      level: SettingLevel.SystemAdminReadonly,
      label: "Max Failed Login Attempts",
      group: "authentication-settings",
      sortOrder: 110,
      controlType: "numeric",
      helpText: "Maximum failed login attempts allowed before a user is considered blocked.",
    },
    {
      moduleName: "solid-core",
      key: "forceChangePasswordOnFirstLogin",
      value: false,
      level: SettingLevel.SystemAdminEditable,
      label: "Force Change Password On First Login",
      group: "authentication-settings",
      sortOrder: 120,
      controlType: "boolean",
      helpText: "Requires users to choose a new password the first time they sign in.",
    },
    {
      moduleName: "solid-core",
      key: "authenticationPasswordRegex",
      value:
        process.env.PASSWORD_REGEX ||
        "^$|^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^\\da-zA-Z]).*$",
      level: SettingLevel.SystemAdminEditable,
      label: "Authentication Password Regex",
      group: "authentication-settings",
      sortOrder: 130,
      controlType: "shortText",
      helpText: "Validation pattern applied to new passwords in registration and password-change flows.",
    },
    {
      moduleName: "solid-core",
      key: "authenticationPasswordRegexErrorMessage",
      value:
        process.env.PASSWORD_REGEX_ERROR_MESSAGE ||
        "Password must contain at least one uppercase, one lowercase, one number, and one special character.",
      level: SettingLevel.SystemAdminEditable,
      label: "Password Regex Error Message",
      group: "authentication-settings",
      sortOrder: 140,
      controlType: "longText",
      helpText: "Custom error message shown when a password does not satisfy the configured regex.",
    },
    {
      moduleName: "solid-core",
      key: "authenticationPasswordComplexityDescription",
      value:
        process.env.PASSWORD_COMPLEXITY_DESC ||
        "Password must contain at least one uppercase, one lowercase, one number, and one special character.",
      level: SettingLevel.SystemAdminEditable,
      label: "Password Complexity Description",
      group: "authentication-settings",
      sortOrder: 150,
      controlType: "longText",
      helpText: "Human-friendly guidance shown to users so they understand the password policy before submission.",
    },
    {
      moduleName: "solid-core",
      key: "iamAutoGeneratedPassword",
      value: process.env.IAM_AUTOGENERATED_PASSWORD || true,
      level: SettingLevel.SystemAdminEditable,
      label: "Auto Generate Password",
      group: "authentication-settings",
      sortOrder: 160,
      controlType: "boolean",
      helpText: "Enables automatic password generation in flows that create user credentials on the user's behalf.",
    },
    {
      moduleName: "solid-core",
      key: "passwordPepper",
      value: process.env.IAM_PASSWORD_PEPPER || "",
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "showNameFieldsForRegistration",
      value:
        process.env.IAM_SHOW_NAME_FIELDS_FOR_REGISTRATION === "true"
          ? true
          : false,
      level: SettingLevel.SystemAdminEditable,
      label: "Show Name Fields For Registration",
      group: "authentication-settings",
      sortOrder: 170,
      controlType: "boolean",
      helpText: "Adds name fields to the public registration form so users can provide profile details up front.",
    },
    {
      moduleName: "solid-core",
      key: "sendWelcomeEmailOnSignup",
      value:
        (
          process.env.IAM_SEND_WELCOME_EMAIL_ON_SIGNUP ?? "false"
        ).toLowerCase() === "true",
      level: SettingLevel.SystemAdminEditable,
      label: "Send Welcome Email On Signup",
      group: "authentication-settings",
      sortOrder: 180,
      controlType: "boolean",
      helpText: "Sends a welcome email after a successful signup when email delivery is configured.",
    },
    {
      moduleName: "solid-core",
      key: "sendWelcomeSmsOnSignup",
      value:
        (
          process.env.IAM_SEND_WELCOME_SMS_ON_SIGNUP ?? "false"
        ).toLowerCase() === "true",
      level: SettingLevel.SystemAdminEditable,
      label: "Send Welcome SMS On Signup",
      group: "authentication-settings",
      sortOrder: 190,
      controlType: "boolean",
      helpText: "Sends a welcome SMS after a successful signup when SMS delivery is configured.",
    },
    {
      moduleName: "solid-core",
      key: "frontendLoginPageUrl",
      value: process.env.IAM_FRONTEND_APP_LOGIN_PAGE_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "Frontend Login Page URL",
      group: "authentication-settings",
      sortOrder: 180,
      controlType: "shortText",
      helpText: "Frontend login page URL used in backend-generated links and redirects.",
    },
    {
      moduleName: "solid-core",
      key: "frontendForgotPasswordPageUrl",
      value: process.env.IAM_FRONTEND_APP_FORGOT_PASSWORD_PAGE_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "Frontend Forgot Password Page URL",
      group: "authentication-settings",
      sortOrder: 190,
      controlType: "shortText",
      helpText: "Frontend forgot-password page URL used in backend-generated links and redirects.",
    },

    // jwt-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "secret",
      value: process.env.IAM_JWT_SECRET,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "audience",
      value: process.env.IAM_JWT_TOKEN_AUDIENCE,
      level: SettingLevel.SystemAdminReadonly,
      label: "JWT Audience",
      group: "jwt-settings",
      sortOrder: 10,
      controlType: "shortText",
      helpText: "JWT audience claim expected by tokens issued by this deployment.",
    },
    {
      moduleName: "solid-core",
      key: "issuer",
      value: process.env.IAM_JWT_TOKEN_ISSUER,
      level: SettingLevel.SystemAdminReadonly,
      label: "JWT Issuer",
      group: "jwt-settings",
      sortOrder: 20,
      controlType: "shortText",
      helpText: "JWT issuer claim attached to tokens issued by this deployment.",
    },
    {
      moduleName: "solid-core",
      key: "accessTokenTtl",
      value: parseInt(
        process.env.IAM_JWT_ACCESS_TOKEN_TTL ?? (isProd ? "1200" : "86400"),
        10,
      ),
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "refreshTokenTtl",
      value: parseInt(process.env.IAM_JWT_REFRESH_TOKEN_TTL ?? "604800", 10),
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "preventConcurrentLogins",
      value: false,
      level: SettingLevel.SystemAdminEditable,
      label: "Prevent Concurrent Logins",
      group: "authentication-settings",
      sortOrder: 200,
      controlType: "boolean",
    },
    {
      moduleName: "solid-core",
      key: "mpinEnabled",
      value: false,
      level: SettingLevel.SystemAdminEditable,
      label: "Enable MPIN Sign-in",
      group: "authentication-settings",
      sortOrder: 210,
      controlType: "boolean",
      helpText:
        "Allows users to set a short device PIN for faster sign-in. Every MPIN route returns 404 while this is off.",
    },
    {
      moduleName: "solid-core",
      key: "mpinRegex",
      value: process.env.IAM_MPIN_REGEX ?? "^\\d{4,6}$",
      level: SettingLevel.SystemAdminEditable,
      label: "MPIN Format",
      group: "authentication-settings",
      sortOrder: 211,
      controlType: "shortText",
      helpText:
        "Regular expression the MPIN must match. Sole authority on MPIN length - the default allows 4 to 6 digits. Predictable PINs (repeated or sequential digits) are rejected separately.",
    },
    {
      moduleName: "solid-core",
      key: "mpinMaxFailedAttempts",
      value: parseInt(process.env.IAM_MPIN_MAX_FAILED_ATTEMPTS ?? "5", 10),
      level: SettingLevel.SystemAdminEditable,
      label: "MPIN Attempts Before Lockout",
      group: "authentication-settings",
      sortOrder: 212,
      controlType: "numeric",
      helpText:
        "Cumulative failed attempts that trigger a temporary lockout. The counter resets only on a successful MPIN sign-in, not when the lockout expires.",
    },
    {
      moduleName: "solid-core",
      key: "mpinLockoutDuration",
      value: parseInt(process.env.IAM_MPIN_LOCKOUT_DURATION ?? "900", 10),
      level: SettingLevel.SystemAdminEditable,
      label: "MPIN Lockout Duration (seconds)",
      group: "authentication-settings",
      sortOrder: 213,
      controlType: "numeric",
      helpText: "How long the temporary lockout lasts.",
    },
    {
      moduleName: "solid-core",
      key: "mpinMaxTotalFailedAttempts",
      value: parseInt(process.env.IAM_MPIN_MAX_TOTAL_FAILED_ATTEMPTS ?? "10", 10),
      level: SettingLevel.SystemAdminEditable,
      label: "MPIN Attempts Before Permanent Deactivation",
      group: "authentication-settings",
      sortOrder: 214,
      controlType: "numeric",
      helpText:
        "Cumulative failed attempts that permanently disable MPIN on that device. Must exceed the lockout threshold. The account itself is never locked - the user signs in normally and sets MPIN up again.",
    },
    {
      moduleName: "solid-core",
      key: "mpinMaxDevicesPerUser",
      value: parseInt(process.env.IAM_MPIN_MAX_DEVICES_PER_USER ?? "5", 10),
      level: SettingLevel.SystemAdminEditable,
      label: "Max MPIN Devices Per User",
      group: "authentication-settings",
      sortOrder: 215,
      controlType: "numeric",
      helpText:
        "At the cap the least recently used credential is evicted rather than the setup rejected, so repeated app reinstalls cannot lock a user out of MPIN setup.",
    },
    // queues-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "queuesDefaultBroker",
      value: process.env.QUEUES_DEFAULT_BROKER || "database",
      level: SettingLevel.SystemAdminReadonly,
      label: "Queues Default Broker",
      group: "queue-settings",
      sortOrder: 10,
      controlType: "selectionStatic",
      options: [
        { label: "Database", value: "database" },
        { label: "RabbitMQ", value: "rabbitmq" },
      ],
      helpText: "Default queue broker used for background job processing.",
    },
    {
      moduleName: "solid-core",
      key: "queuesServiceRole",
      value: process.env.QUEUES_SERVICE_ROLE,
      level: SettingLevel.SystemAdminReadonly,
      label: "Queues Service Role",
      group: "queue-settings",
      sortOrder: 20,
      controlType: "shortText",
      helpText: "Service role or worker identity expected by the queue subsystem.",
    },
    {
      moduleName: "solid-core",
      key: "queuesRabbitMqUrl",
      value: process.env.QUEUES_RABBIT_MQ_URL,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "solidCliRunning",
      value: process.env.SOLID_CLI_RUNNING || "false",
      level: SettingLevel.SystemEnv,
    },

    // sms-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "smsProvider",
      value: process.env.COMMON_SMS_PROVIDER,
      level: SettingLevel.SystemAdminReadonly,
      label: "SMS Provider",
      group: "sms-settings",
      sortOrder: 10,
      controlType: "shortText",
      helpText: "SMS delivery provider currently configured for outbound messages.",
    },
    {
      moduleName: "solid-core",
      key: "smsTemplateSeederFiles",
      value: process.env.COMMON_SMS_TEMPLATE_SEEDER_FILES,
      level: SettingLevel.SystemAdminReadonly,
      label: "SMS Template Seeder Files",
      group: "sms-settings",
      sortOrder: 20,
      controlType: "longText",
      helpText: "Comma-separated list of SMS template seed files loaded by the platform.",
    },
    {
      moduleName: "solid-core",
      key: "shouldQueueSms",
      value: (process.env.COMMON_SMS_SHOULD_QUEUE ?? "false") === "true",
      level: SettingLevel.SystemAdminReadonly,
      label: "Queue SMS",
      group: "sms-settings",
      sortOrder: 30,
      controlType: "boolean",
      helpText: "Whether outbound SMS messages are queued for asynchronous delivery instead of being sent inline.",
    },
    {
      moduleName: "solid-core",
      key: "msg91SmsUrl",
      value: process.env.COMMON_MSG91_SMS_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "MSG91 SMS URL",
      group: "sms-settings",
      sortOrder: 40,
      controlType: "shortText",
      helpText: "MSG91 endpoint URL used when the MSG91 SMS provider is active.",
    },
    {
      moduleName: "solid-core",
      key: "msg91SmsApiKey",
      value: process.env.COMMON_MSG91_SMS_API_KEY,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "twilioAccountSid",
      value: process.env.COMMON_TWILIO_ACCOUNT_SID,
      level: SettingLevel.SystemAdminReadonly,
      label: "Twilio Account SID",
      group: "sms-settings",
      sortOrder: 50,
      controlType: "shortText",
      helpText: "Twilio account SID used when the Twilio SMS provider is active.",
    },
    {
      moduleName: "solid-core",
      key: "twilioAuthToken",
      value: process.env.COMMON_TWILIO_AUTH_TOKEN,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "twilioNumber",
      value: process.env.COMMON_TWILIO_NUMBER,
      level: SettingLevel.SystemAdminReadonly,
      label: "Twilio Number",
      group: "sms-settings",
      sortOrder: 60,
      controlType: "shortText",
      helpText: "Twilio phone number used as the sender for outbound SMS.",
    },

    // tiny-url-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "tinyUrlApiUrl",
      value: process.env.COMMON_SHORT_URL_API_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "Tiny URL API URL",
      group: "short-url-settings",
      sortOrder: 10,
      controlType: "shortText",
      helpText: "API endpoint used to create shortened URLs.",
    },
    {
      moduleName: "solid-core",
      key: "tinyUrlApiKey",
      value: process.env.COMMON_SHORT_URL_API_KEY,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "tinyUrlDomain",
      value: process.env.COMMON_SHORT_URL_DOMAIN,
      level: SettingLevel.SystemAdminReadonly,
      label: "Tiny URL Domain",
      group: "short-url-settings",
      sortOrder: 20,
      controlType: "shortText",
      helpText: "Short URL domain used when generating branded or provider-backed tiny URLs.",
    },
    {
      moduleName: "solid-core",
      key: "tinyUrlEnabled",
      value: (process.env.COMMON_SHORT_URL_ENABLED ?? "false") === "true",
      level: SettingLevel.SystemAdminReadonly,
      label: "Tiny URL Enabled",
      group: "short-url-settings",
      sortOrder: 30,
      controlType: "boolean",
      helpText: "Indicates whether short URL generation is enabled for this deployment.",
    },

    // whatsapp-settings-provider.service.ts
    {
      moduleName: "solid-core",
      key: "whatsappProvider",
      value: process.env.COMMON_WHATSAPP_PROVIDER,
      level: SettingLevel.SystemAdminReadonly,
      label: "WhatsApp Provider",
      group: "whatsapp-settings",
      sortOrder: 10,
      controlType: "shortText",
      helpText: "WhatsApp delivery provider currently configured for outbound messages.",
    },
    {
      moduleName: "solid-core",
      key: "msg91WhatsappUrl",
      value: process.env.COMMON_WHATSAPP_API_URL,
      level: SettingLevel.SystemAdminReadonly,
      label: "MSG91 WhatsApp URL",
      group: "whatsapp-settings",
      sortOrder: 20,
      controlType: "shortText",
      helpText: "MSG91 endpoint URL used when the MSG91 WhatsApp provider is active.",
    },
    {
      moduleName: "solid-core",
      key: "msg91WhatsappApiKey",
      value: process.env.COMMON_WHATSAPP_API_KEY,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "msg91WhatsappIntegratedNumber",
      value: process.env.COMMON_WHATSAPP_INTEGRATED_NUMBER,
      level: SettingLevel.SystemAdminReadonly,
      label: "MSG91 WhatsApp Integrated Number",
      group: "whatsapp-settings",
      sortOrder: 30,
      controlType: "shortText",
      helpText: "Integrated WhatsApp number used by the MSG91 WhatsApp provider.",
    },
    {
      moduleName: "solid-core",
      key: "metaWhatsappApiUrl",
      value: process.env.COMMON_META_WHATSAPP_API_URL || "https://graph.facebook.com",
      level: SettingLevel.SystemAdminReadonly,
      label: "Meta WhatsApp API URL",
      group: "whatsapp-settings",
      sortOrder: 40,
      controlType: "shortText",
      helpText: "Base Meta WhatsApp API URL used by the Meta WhatsApp integration.",
    },
    {
      moduleName: "solid-core",
      key: "metaWhatsappApiVersion",
      value: process.env.COMMON_META_WHATSAPP_API_VERSION || "v23.0",
      level: SettingLevel.SystemAdminReadonly,
      label: "Meta WhatsApp API Version",
      group: "whatsapp-settings",
      sortOrder: 50,
      controlType: "shortText",
      helpText: "Meta WhatsApp API version used when building outbound requests.",
    },
    {
      moduleName: "solid-core",
      key: "metaWhatsappPhoneNumberId",
      value: process.env.COMMON_META_WHATSAPP_PHONE_NUMBER_ID,
      level: SettingLevel.SystemAdminReadonly,
      label: "Meta WhatsApp Phone Number ID",
      group: "whatsapp-settings",
      sortOrder: 60,
      controlType: "shortText",
      helpText: "Meta WhatsApp phone number ID used to send messages from the connected business account.",
    },
    {
      moduleName: "solid-core",
      key: "metaWhatsappBusinessAccountId",
      value: process.env.COMMON_META_WHATSAPP_BUSINESS_ACCOUNT_ID,
      level: SettingLevel.SystemAdminReadonly,
      label: "Meta WhatsApp Business Account ID",
      group: "whatsapp-settings",
      sortOrder: 70,
      controlType: "shortText",
      helpText: "Meta WhatsApp business account ID associated with the connected sender.",
    },
    {
      moduleName: "solid-core",
      key: "metaWhatsappAccessToken",
      value: process.env.COMMON_META_WHATSAPP_ACCESS_TOKEN,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "metaWhatsappWebhookVerifyToken",
      value: process.env.COMMON_META_WHATSAPP_WEBHOOK_VERIFY_TOKEN,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "metaWhatsappAppSecret",
      value: process.env.COMMON_META_WHATSAPP_APP_SECRET,
      level: SettingLevel.SystemEnv,
    },
    {
      moduleName: "solid-core",
      key: "uiTestDefaultTimeoutMs",
      value: timeoutFromEnv(process.env.COMMON_UI_TEST_DEFAULT_TIMEOUT_MS, 30000),
      level: SettingLevel.SystemAdminEditable,
      label: "UI Test Default Timeout (ms)",
      group: "testing-settings",
      sortOrder: 10,
      controlType: "numeric",
      helpText: "How long UI test steps wait for an element before failing. Raise this if tests time out on slow screens. Overridden by the --ui-timeout-ms flag and by a per-step timeoutMs.",
    },
    {
      moduleName: "solid-core",
      key: "uiTestNavigationTimeoutMs",
      value: timeoutFromEnv(
        process.env.COMMON_UI_TEST_NAVIGATION_TIMEOUT_MS,
        timeoutFromEnv(process.env.COMMON_UI_TEST_DEFAULT_TIMEOUT_MS, 30000),
      ),
      level: SettingLevel.SystemAdminEditable,
      label: "UI Test Navigation Timeout (ms)",
      group: "testing-settings",
      sortOrder: 20,
      controlType: "numeric",
      helpText: "How long the ui.goto step waits for a page to load before failing. Falls back to the UI test default timeout.",
    },
    {
      moduleName: "solid-core",
      key: "uiTestBrowsersEagerInstall",
      value: process.env.COMMON_UI_TEST_BROWSERS_EAGER_INSTALL === "true",
      level: SettingLevel.SystemEnv,
    },
  ] as const satisfies SettingDefinition[];

// 2.
export type SolidCoreSetting = ReturnType<
  typeof getSolidCoreSettings
>[number]["key"];

// 3.
@SettingsProvider()
@Injectable()
export class SolidCoreDefaultSettingsProvider implements ISettingsProvider {
  getSettings() {
    const isProd = (process.env.ENV as Environment) === Environment.Production;
    return getSolidCoreSettings(isProd);
  }
}
