import { Injectable } from "@nestjs/common";
import { DataSource } from "typeorm";
import {
    DatasourceIntrospectionColumn,
    DatasourceIntrospectionProvider,
    DatasourceIntrospectionTableRef,
} from "src/interfaces/datasource-introspection-provider.interface";

@Injectable()
export class MssqlDatasourceIntrospectionProviderService implements DatasourceIntrospectionProvider {
    readonly type = "mssql";

    supports(type: string) {
        return type?.toLowerCase() === this.type;
    }

    async listTables(dataSource: DataSource): Promise<DatasourceIntrospectionTableRef[]> {
        const rows = await dataSource.query(`
            SELECT
                TABLE_SCHEMA AS tableSchema,
                TABLE_NAME AS tableName
            FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_TYPE = 'BASE TABLE'
              AND TABLE_SCHEMA NOT IN ('sys', 'INFORMATION_SCHEMA')
            ORDER BY TABLE_SCHEMA, TABLE_NAME
        `);

        return rows.map((row: any) => ({
            tableSchema: row.tableSchema ?? null,
            tableName: row.tableName,
        }));
    }

    async listColumns(dataSource: DataSource): Promise<DatasourceIntrospectionColumn[]> {
        const rows = await dataSource.query(`
            SELECT
                schema_name(t.schema_id) AS tableSchema,
                t.name AS tableName,
                c.name AS columnName,
                ty.name AS dataType,
                c.is_identity AS isAutoGenerated,
                CASE WHEN pk.column_id IS NOT NULL THEN 1 ELSE 0 END AS isPrimaryKey,
                CASE WHEN c.is_nullable = 1 THEN 'YES' ELSE 'NO' END AS isNullable,
                dc.definition AS defaultValue,
                CASE
                    WHEN ty.name IN ('nchar', 'nvarchar') AND c.max_length > 0 THEN c.max_length / 2
                    ELSE c.max_length
                END AS characterMaximumLength,
                c.precision AS numericPrecision,
                c.scale AS numericScale,
                c.column_id AS ordinalPosition
            FROM sys.tables t
            INNER JOIN sys.columns c ON c.object_id = t.object_id
            INNER JOIN sys.types ty ON ty.user_type_id = c.user_type_id
            LEFT JOIN sys.default_constraints dc ON dc.object_id = c.default_object_id
            LEFT JOIN (
                SELECT ic.object_id, ic.column_id
                FROM sys.index_columns ic
                INNER JOIN sys.key_constraints kc
                    ON kc.parent_object_id = ic.object_id
                   AND kc.unique_index_id = ic.index_id
                WHERE kc.type = 'PK'
            ) pk
                ON pk.object_id = c.object_id
               AND pk.column_id = c.column_id
            WHERE schema_name(t.schema_id) NOT IN ('sys', 'INFORMATION_SCHEMA')
            ORDER BY schema_name(t.schema_id), t.name, c.column_id
        `);

        return rows.map((row: any) => ({
            tableSchema: row.tableSchema ?? null,
            tableName: row.tableName,
            columnName: row.columnName,
            dataType: row.dataType,
            isAutoGenerated: Boolean(row.isAutoGenerated),
            isPrimaryKey: Boolean(row.isPrimaryKey),
            isNullable: String(row.isNullable).toUpperCase() === "YES",
            defaultValue: row.defaultValue ?? null,
            characterMaximumLength: this.toNumberOrNull(row.characterMaximumLength),
            numericPrecision: this.toNumberOrNull(row.numericPrecision),
            numericScale: this.toNumberOrNull(row.numericScale),
            ordinalPosition: this.toNumberOrNull(row.ordinalPosition),
        }));
    }

    async getTableDefinition(dataSource: DataSource, table: DatasourceIntrospectionTableRef): Promise<string | null> {
        const rows = await dataSource.query(
            `
                DECLARE @schemaName NVARCHAR(128) = @0;
                DECLARE @tableName NVARCHAR(128) = @1;

                WITH target_table AS (
                    SELECT t.object_id, s.name AS schema_name, t.name AS table_name
                    FROM sys.tables t
                    INNER JOIN sys.schemas s ON s.schema_id = t.schema_id
                    WHERE t.name = @tableName
                      AND (@schemaName IS NULL OR s.name = @schemaName)
                ),
                column_lines AS (
                    SELECT
                        c.column_id,
                        '    [' + c.name + '] '
                        + UPPER(ty.name)
                        + CASE
                            WHEN ty.name IN ('varchar', 'char', 'varbinary', 'binary') THEN
                                '(' + CASE WHEN c.max_length = -1 THEN 'MAX' ELSE CAST(c.max_length AS VARCHAR(16)) END + ')'
                            WHEN ty.name IN ('nvarchar', 'nchar') THEN
                                '(' + CASE WHEN c.max_length = -1 THEN 'MAX' ELSE CAST(c.max_length / 2 AS VARCHAR(16)) END + ')'
                            WHEN ty.name IN ('decimal', 'numeric') THEN
                                '(' + CAST(c.precision AS VARCHAR(16)) + ',' + CAST(c.scale AS VARCHAR(16)) + ')'
                            WHEN ty.name IN ('datetime2', 'datetimeoffset', 'time') THEN
                                '(' + CAST(c.scale AS VARCHAR(16)) + ')'
                            ELSE
                                ''
                          END
                        + CASE
                            WHEN ic.object_id IS NOT NULL THEN
                                ' IDENTITY(' + CAST(CONVERT(BIGINT, ic.seed_value) AS VARCHAR(32)) + ',' + CAST(CONVERT(BIGINT, ic.increment_value) AS VARCHAR(32)) + ')'
                            ELSE
                                ''
                          END
                        + CASE
                            WHEN dc.definition IS NOT NULL THEN ' DEFAULT ' + dc.definition
                            ELSE ''
                          END
                        + CASE
                            WHEN c.is_nullable = 1 THEN ' NULL'
                            ELSE ' NOT NULL'
                          END AS line
                    FROM target_table tt
                    INNER JOIN sys.columns c ON c.object_id = tt.object_id
                    INNER JOIN sys.types ty ON ty.user_type_id = c.user_type_id
                    LEFT JOIN sys.identity_columns ic
                        ON ic.object_id = c.object_id
                       AND ic.column_id = c.column_id
                    LEFT JOIN sys.default_constraints dc ON dc.object_id = c.default_object_id
                ),
                constraint_lines AS (
                    SELECT
                        kc.name AS constraint_name,
                        '    CONSTRAINT [' + kc.name + '] PRIMARY KEY ('
                        + STUFF((
                            SELECT ', [' + c.name + ']'
                            FROM sys.index_columns ic
                            INNER JOIN sys.columns c
                                ON c.object_id = ic.object_id
                               AND c.column_id = ic.column_id
                            WHERE ic.object_id = kc.parent_object_id
                              AND ic.index_id = kc.unique_index_id
                            ORDER BY ic.key_ordinal
                            FOR XML PATH(''), TYPE
                        ).value('.', 'NVARCHAR(MAX)'), 1, 2, '')
                        + ')' AS line
                    FROM target_table tt
                    INNER JOIN sys.key_constraints kc ON kc.parent_object_id = tt.object_id
                    WHERE kc.type = 'PK'
                )
                SELECT
                    'CREATE TABLE [' + tt.schema_name + '].[' + tt.table_name + '] (' + CHAR(10)
                    + ISNULL((
                        SELECT STUFF((
                            SELECT ',' + CHAR(10) + cl.line
                            FROM column_lines cl
                            ORDER BY cl.column_id
                            FOR XML PATH(''), TYPE
                        ).value('.', 'NVARCHAR(MAX)'), 1, 2, '')
                    ), '')
                    + ISNULL((
                        SELECT CASE
                            WHEN EXISTS (SELECT 1 FROM constraint_lines)
                                THEN ',' + CHAR(10) + STUFF((
                                    SELECT ',' + CHAR(10) + cn.line
                                    FROM constraint_lines cn
                                    ORDER BY cn.constraint_name
                                    FOR XML PATH(''), TYPE
                                ).value('.', 'NVARCHAR(MAX)'), 1, 2, '')
                            ELSE ''
                        END
                    ), '')
                    + CHAR(10) + ');' AS ddl
                FROM target_table tt
            `,
            [table.tableSchema, table.tableName],
        );

        return rows?.[0]?.ddl ?? null;
    }

    private toNumberOrNull(value: unknown) {
        if (value === null || value === undefined || value === "") {
            return null;
        }

        const parsed = Number(value);
        return Number.isFinite(parsed) ? parsed : null;
    }
}
