import { Injectable } from "@nestjs/common";
import { DataSource } from "typeorm";
import {
    DatasourceIntrospectionColumn,
    DatasourceIntrospectionProvider,
    DatasourceIntrospectionTableRef,
} from "src/interfaces/datasource-introspection-provider.interface";

@Injectable()
export class MysqlDatasourceIntrospectionProviderService implements DatasourceIntrospectionProvider {
    readonly type = "mysql";

    supports(type: string) {
        return type?.toLowerCase() === this.type;
    }

    async listTables(dataSource: DataSource): Promise<DatasourceIntrospectionTableRef[]> {
        const rows = await dataSource.query(`
            SELECT
                TABLE_SCHEMA AS tableSchema,
                TABLE_NAME AS tableName
            FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_TYPE = 'BASE TABLE'
              AND TABLE_SCHEMA = DATABASE()
            ORDER BY TABLE_SCHEMA, TABLE_NAME
        `);

        return rows.map((row: any) => ({
            tableSchema: row.tableSchema ?? null,
            tableName: row.tableName,
        }));
    }

    async listColumns(dataSource: DataSource): Promise<DatasourceIntrospectionColumn[]> {
        const rows = await dataSource.query(`
            SELECT
                TABLE_SCHEMA AS tableSchema,
                TABLE_NAME AS tableName,
                COLUMN_NAME AS columnName,
                DATA_TYPE AS dataType,
                EXTRA AS extra,
                COLUMN_KEY AS columnKey,
                IS_NULLABLE AS isNullable,
                COLUMN_DEFAULT AS defaultValue,
                CHARACTER_MAXIMUM_LENGTH AS characterMaximumLength,
                NUMERIC_PRECISION AS numericPrecision,
                NUMERIC_SCALE AS numericScale,
                ORDINAL_POSITION AS ordinalPosition
            FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
            ORDER BY TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION
        `);

        return rows.map((row: any) => ({
            tableSchema: row.tableSchema ?? null,
            tableName: row.tableName,
            columnName: row.columnName,
            dataType: row.dataType,
            isAutoGenerated: String(row.extra ?? "").toLowerCase().includes("auto_increment"),
            isPrimaryKey: String(row.columnKey ?? "").toUpperCase() === "PRI",
            isNullable: String(row.isNullable).toUpperCase() === "YES",
            defaultValue: row.defaultValue ?? null,
            characterMaximumLength: this.toNumberOrNull(row.characterMaximumLength),
            numericPrecision: this.toNumberOrNull(row.numericPrecision),
            numericScale: this.toNumberOrNull(row.numericScale),
            ordinalPosition: this.toNumberOrNull(row.ordinalPosition),
        }));
    }

    async getTableDefinition(dataSource: DataSource, table: DatasourceIntrospectionTableRef): Promise<string | null> {
        const schemaName = table.tableSchema ?? dataSource.options.database;
        const rows = await dataSource.query(
            `SHOW CREATE TABLE \`${schemaName}\`.\`${table.tableName}\``,
        );

        const firstRow = rows?.[0];
        if (!firstRow || typeof firstRow !== "object") {
            return null;
        }

        const ddlKey = Object.keys(firstRow).find((key) => key.toLowerCase().startsWith("create table"));
        if (!ddlKey) {
            return null;
        }

        return String(firstRow[ddlKey] ?? "").trim() || null;
    }

    private toNumberOrNull(value: unknown) {
        if (value === null || value === undefined || value === "") {
            return null;
        }

        const parsed = Number(value);
        return Number.isFinite(parsed) ? parsed : null;
    }
}
