import { Injectable } from "@nestjs/common";
import { DataSource } from "typeorm";
import {
    DatasourceIntrospectionColumn,
    DatasourceIntrospectionProvider,
    DatasourceIntrospectionTableRef,
} from "src/interfaces/datasource-introspection-provider.interface";

@Injectable()
export class PostgresDatasourceIntrospectionProviderService implements DatasourceIntrospectionProvider {
    readonly type = "postgres";

    supports(type: string) {
        return type?.toLowerCase() === this.type;
    }

    async listTables(dataSource: DataSource): Promise<DatasourceIntrospectionTableRef[]> {
        const rows = await dataSource.query(`
            SELECT
                TABLE_SCHEMA AS "tableSchema",
                TABLE_NAME AS "tableName"
            FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_TYPE = 'BASE TABLE'
              AND TABLE_SCHEMA NOT IN ('pg_catalog', 'information_schema')
            ORDER BY TABLE_SCHEMA, TABLE_NAME
        `);

        return rows.map((row: any) => ({
            tableSchema: row.tableSchema ?? null,
            tableName: row.tableName,
        }));
    }

    async listColumns(dataSource: DataSource): Promise<DatasourceIntrospectionColumn[]> {
        const rows = await dataSource.query(`
            SELECT
                TABLE_SCHEMA AS "tableSchema",
                TABLE_NAME AS "tableName",
                COLUMN_NAME AS "columnName",
                DATA_TYPE AS "dataType",
                CASE
                    WHEN is_identity = 'YES' THEN true
                    WHEN COLUMN_DEFAULT LIKE 'nextval(%' THEN true
                    ELSE false
                END AS "isAutoGenerated",
                IS_NULLABLE AS "isNullable",
                COLUMN_DEFAULT AS "defaultValue",
                CHARACTER_MAXIMUM_LENGTH AS "characterMaximumLength",
                NUMERIC_PRECISION AS "numericPrecision",
                NUMERIC_SCALE AS "numericScale",
                ORDINAL_POSITION AS "ordinalPosition"
            FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA NOT IN ('pg_catalog', 'information_schema')
            ORDER BY TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION
        `);

        return rows.map((row: any) => ({
            tableSchema: row.tableSchema ?? null,
            tableName: row.tableName,
            columnName: row.columnName,
            dataType: row.dataType,
            isAutoGenerated: Boolean(row.isAutoGenerated),
            isNullable: String(row.isNullable).toUpperCase() === "YES",
            defaultValue: row.defaultValue ?? null,
            characterMaximumLength: this.toNumberOrNull(row.characterMaximumLength),
            numericPrecision: this.toNumberOrNull(row.numericPrecision),
            numericScale: this.toNumberOrNull(row.numericScale),
            ordinalPosition: this.toNumberOrNull(row.ordinalPosition),
        }));
    }

    async getTableDefinition(dataSource: DataSource, table: DatasourceIntrospectionTableRef): Promise<string | null> {
        const rows = await dataSource.query(
            `
                WITH target_table AS (
                    SELECT c.oid, n.nspname AS schema_name, c.relname AS table_name
                    FROM pg_class c
                    INNER JOIN pg_namespace n ON n.oid = c.relnamespace
                    WHERE c.relkind = 'r'
                      AND c.relname = $1
                      AND ($2::text IS NULL OR n.nspname = $2)
                    LIMIT 1
                ),
                column_lines AS (
                    SELECT
                        a.attnum,
                        format(
                            '    %I %s%s%s%s',
                            a.attname,
                            format_type(a.atttypid, a.atttypmod),
                            CASE
                                WHEN a.attidentity = 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
                                WHEN a.attidentity = 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
                                ELSE ''
                            END,
                            CASE
                                WHEN ad.adbin IS NOT NULL THEN ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid)
                                ELSE ''
                            END,
                            CASE
                                WHEN a.attnotnull THEN ' NOT NULL'
                                ELSE ''
                            END
                        ) AS line
                    FROM target_table tt
                    INNER JOIN pg_attribute a ON a.attrelid = tt.oid
                    LEFT JOIN pg_attrdef ad
                        ON ad.adrelid = a.attrelid
                       AND ad.adnum = a.attnum
                    WHERE a.attnum > 0
                      AND NOT a.attisdropped
                ),
                constraint_lines AS (
                    SELECT
                        c.conname,
                        format('    CONSTRAINT %I %s', c.conname, pg_get_constraintdef(c.oid, true)) AS line
                    FROM target_table tt
                    INNER JOIN pg_constraint c ON c.conrelid = tt.oid
                    WHERE c.contype IN ('p', 'u', 'f', 'c')
                )
                SELECT format(
                    'CREATE TABLE %I.%I (\n%s%s\n);',
                    tt.schema_name,
                    tt.table_name,
                    COALESCE(
                        (
                            SELECT string_agg(line, ',\n' ORDER BY attnum)
                            FROM column_lines
                        ),
                        ''
                    ),
                    COALESCE(
                        (
                            SELECT CASE
                                WHEN EXISTS (SELECT 1 FROM constraint_lines)
                                    THEN ',\n' || string_agg(line, ',\n' ORDER BY conname)
                                ELSE ''
                            END
                            FROM constraint_lines
                        ),
                        ''
                    )
                ) AS ddl
                FROM target_table tt
            `,
            [table.tableName, table.tableSchema],
        );

        return rows?.[0]?.ddl ?? null;
    }

    private toNumberOrNull(value: unknown) {
        if (value === null || value === undefined || value === "") {
            return null;
        }

        const parsed = Number(value);
        return Number.isFinite(parsed) ? parsed : null;
    }
}
