import { DataSource } from "typeorm";

export type DatasourceIntrospectionTableRef = {
    tableSchema: string | null;
    tableName: string;
};

export type DatasourceIntrospectionColumn = {
    tableSchema: string | null;
    tableName: string;
    columnName: string;
    dataType: string;
    isAutoGenerated: boolean;
    isPrimaryKey: boolean;
    isNullable: boolean;
    defaultValue: string | null;
    characterMaximumLength: number | null;
    numericPrecision: number | null;
    numericScale: number | null;
    ordinalPosition: number | null;
};

export interface DatasourceIntrospectionProvider {
    readonly type: string;
    supports(type: string): boolean;
    listTables(dataSource: DataSource): Promise<DatasourceIntrospectionTableRef[]>;
    listColumns(dataSource: DataSource): Promise<DatasourceIntrospectionColumn[]>;
    getTableDefinition(dataSource: DataSource, table: DatasourceIntrospectionTableRef): Promise<string | null>;
}
